using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Vocab.Listas
{
    class ListaSubstantivos12
    {
        List<string> ListaSubstantivo12 = new List<string> {
            "WATTLE AND DAUB",  "Building Material Consisting Of Interwoven Rods And Twigs Covered With Clay ",
"STIFFENER",    "Material Used For Stiffening Something ",
"STREPTODORNASE",   "An Enzyme Produced By Some Hemolytic Strains Of Streptococcus That Dissolves Fibrinous Secretions From Infections",
"STREPTOKINASE",    "An Enzyme Produced By Some Strains Of Streptococcus That Can Liquefy Blood Clots By Converting Plasminogen To Plasmin",
"STREPTOLYSIN", "Any Of Several Hemolysins Derived From Strains Of Streptococcus ",
"STRIPPER", "A Chemical Compound Used To Remove Paint Or Varnish ",
"STROPHANTHIN", "A Bitter And Very Toxic Glycoside Derived From Plants Of The Genus Strophanthus",
"STRONTIANITE", "A Mineral Consisting Of Strontium Carbonate ",
"STUCCO",   "A Plaster Now Made Mostly From Portland Cement And Sand And Lime",
"SUBLIMATE",    "The Product Of Vaporization Of A Solid ",
"TALLOW",   "Obtained From Suet And Used In Making Soap, Candles And Lubricants ",
"VEGETABLE TALLOW", "A Waxy Fat Obtained From Certain Plants E.G. Bayberry And Used As Tallow ",
"SUCROSE",  "A Complex Carbohydrate Found In Many Plants And Used As A Sweetening Agent ",
"JAGGERY",  "Unrefined Brown Sugar Made From Palm Sap ",
"STRUCTURAL IRON",  "Iron That Has Been Cast Or Worked In Structural Shapes ",
"STRUCTURAL STEEL", "A Strong Steel That Is Rolled Into Shapes That Are Used In Construction ",
"SULFANILIC ACID",  "A Crystalline Acid Made From Aniline And Used As A Dye ",
"SULFATE",  "A Salt Or Ester Of Sulphuric Acid ",
"SULFIDE",  "A Compound Of Sulphur And Some Other Element That Is More Electropositive ",
"SULFUR OXIDE", "Any Of Several Oxides Of Sulphur ",
"SULFUR DIOXIDE",   "A Colorless Toxic Gas So2 That Occurs In The Gases From Volcanoes",
"SULFUR HEXAFLUORIDE",  "A Colorless Gas That Is Soluble In Alcohol And Ether",
"SUNSTONE", "A Translucent Quartz Spangled With Bits Of Mica Or Other Minerals ",
"SUPEROXIDE",   "The Univalent Anion O2-",
"SUPEROXIDE DISMUTASE", "An Enzyme That Catalyzes The Conversion Of Superoxide Into Hydrogen Peroxide And Oxygen",
"SURGICAL SPIRIT",  "Methylated Spirit Used In The Practice Of Medicine Especially For Cleansing The Skin Before Injections Or Before Surgery ",
"SWEDISH IRON", "Wrought Iron Of High Purity Made In Sweden ",
"SWINGING CHAD",    "A Chad That Is Incompletely Removed And Still Attached At Two Corners ",
"SYLVANITE",    "A Silver-White Mineral Consisting Of Silver Gold Telluride",
"SYLVITE",  "A Mineral Consisting Of Native Potassium Chloride",
"TABUN",    "The First Known Nerve Agent, Synthesized By German Chemists In 1936",
"TALC", "A Fine Grained Mineral Having A Soft Soapy Feel And Consisting Of Hydrated Magnesium Silicate",
"FRENCH CHALK", "A Soft White Compact Talc Used To Mark Cloth Or To Remove Grease Stains ",
"RENSSELAERITE",    "A Kind Of Soft Talc",
"TALLOW OIL",   "An Animal Oil Obtained By Pressing Tallow",
"TANNIN",   "Any Of Various Complex Phenolic Substances Of Plant Origin",
"CATECHIN", "A Tannic Acid That Is Extracted From Black Catechu As A White Crystalline Substance ",
"TANTALITE",    "A Mineral Consisting Of Tantalum Oxide Of Iron And Manganese That Occurs With Niobite Or In Coarse Granite",
"TARTARIC ACID",    "An Acid Found In Many Fruits",
"RACEMIC ACID", "The Optically Inactive Form Of Tartaric Acid That Is Often Found In Grape Juice ",
"TEAR GAS", "A Gas That Makes The Eyes Fill With Tears But Does Not Damage Them",
"TELLURIDE",    "Any Binary Compound Of Tellurium With Other More Electropositive Elements ",
"TELOMERASE",   "An Enzyme In Eukaryotic Cells That Can Add Telomeres To The Ends Of Chromosomes After They Divide ",
"TENDERIZER",   "A Substance As The Plant Enzyme Papain Applied To Meat To Make It Tender ",
"TERPENE",  "An Unsaturated Hydrocarbon Obtained From Plants ",
"TETRACHLORIDE",    "Any Compound That Contains Four Chlorine Atoms Per Molecule ",
"TETRAFLUOROETHYLENE",  "A Flammable Gaseous Fluorocarbon Used In Making Plastics Polytetrafluoroethylene Resins ",
"TETRAHALIDE",  "Any Halide Containing Four Halogen Atoms In Its Molecules ",
"TETRASACCHARIDE",  "Any Of A Variety Of Carbohydrates That Yield Four Monosaccharide Molecules On Complete Hydrolysis ",
"TETRODOTOXIN", "A Powerful Neurotoxin Found In The Ovaries Of Pufferfish ",
"TETROXIDE",    "An Oxide Containing Four Atoms Of Oxygen In The Molecule ",
"TETRYL",   "A Yellow Crystalline Explosive Solid That Is Used In Detonators ",
"THATCH",   "Plant Stalks Used As Roofing Material ",
"THICKENING",   "Any Material Used To Thicken",
"THIOURACIL",   "Depresses The Function Of The Thyroid Gland ",
"THIOCYANATE",  "A Salt Of Thiocyanic Acid",
"THIOCYANIC ACID",  "An Unstable Acid That Can Be Obtained By Distilling A Thiocyanate Salt ",
"THORITE",  "A Radioactive Mineral Consisting Of Thorium Silicate",
"THORTVEITITE", "A Mineral Consisting Of Scandium Yttrium Silicate",
"THREONINE",    "A Colorless Crystalline Amino Acid Found In Protein",
"PROTHROMBIN",  "A Protein In Blood Plasma That Is The Inactive Precursor Of Thrombin ",
"THROMBOPLASTIN",   "An Enzyme Liberated From Blood Platelets That Converts Prothrombin Into Thrombin As Blood Starts To Clot ",
"CALCIUM ION",  "Ion Of Calcium",
"PROACCELERIN", "A Coagulation Factor ",
"PROCONVERTIN", "A Coagulation Factor Formed In The Kidney Under The Influence Of Vitamin K ",
"ANTIHEMOPHILIC FACTOR",    "A Coagulation Factor Trade Name Hemofil Whose Absence Is Associated With Hemophilia A ",
"CHRISTMAS FACTOR", "Coagulation Factor Whose Absence Is Associated With Hemophilia B ",
"PROTHROMBINASE",   "Coagulation Factor That Is Converted To An Enzyme That Converts Prothrombin To Thrombin In A Reaction That Depends On Calcium Ions And Other Coagulation Factors ",
"PLASMA THROMBOPLASTIN ANTECEDENT", "Coagulation Factor Whose Deficiency Results In A Hemorrhagic Tendency ",
"HAGEMAN FACTOR",   "Coagulation Factor Whose Deficiency Results In Prolongation Of Clotting Time Of Venous Blood ",
"FIBRINASE",    "In The Clotting Of Blood Thrombin Catalyzes Factor Xiii Into Its Active Form Fibrinase Which Causes Fibrin To Form A Stable Clot ",
"THYMINE",  "A Base Found In Dna But Not In Rna And Derived From Pyrimidine",
"DEOXYADENOSINE",   "A Nucleoside Component Of Dna",
"DEOXYCYTIDINE",    "A Nucleoside Component Of Dna",
"DEOXYGUANOSINE",   "A Nucleoside Component Of Dna",
"DEOXYTHYMIDINE",   "A Nucleoside Component Of Dna",
"THYMOL",   "A Colorless Crystalline Solid Used In Perfume Or Preserving Biological Specimens Or In Embalming Or Medically As A Fungicide Or Antiseptic ",
"MELANOCYTE-STIMULATING HORMONE",   "A Hormone Secreted By The Anterior Pituitary Gland That Controls The Degree Of Pigmentation In Melanocytes ",
"THYROTROPIN",  "Anterior Pituitary Hormone That Stimulates The Function Of The Thyroid Gland ",
"THYROTROPIN-RELEASING HORMONE",    "Hormone Released By The Hypothalamus That Controls The Release Of Thyroid-Stimulating Hormone From The Anterior Pituitary ",
"THYRONINE",    "A Phenolic Amino Acid Of Which Thyroxine Is A Derivative ",
"TILE", "A Thin Flat Slab Of Fired Clay Used For Roofing ",
"TILL", "Unstratified Soil Deposited By A Glacier",
"TISSUE",   "A Soft Thin Usually Translucent Paper ",
"TOILET TISSUE",    "A Soft Thin Absorbent Paper For Use In Toilets ",
"TOILET ROLL",  "A Roll Of Toilet Paper ",
"TOLUENE",  "A Colorless Flammable Liquid Obtained From Petroleum Or Coal Tar",
"TOLUIC ACID",  "An Isomeric Acid Derived From Toluene ",
"TOMBAC",   "An Alloy Of Copper And Zinc And Sometimes Arsenic Used To Imitate Gold In Cheap Jewelry And For Gilding ",
"TONER",    "A Black Or Colored Powder Used In A Printer To Develop A Xerographic Image ",
"TOOL STEEL",   "Alloy Steel That Is Suitable For Making Tools",
"TOPAZ",    "A Mineral Fluosilicate Of Aluminum That Occurs In Crystals Of Various Colors And Is Used As A Gemstone ",
"TOURMALINE",   "A Mineral That Is A Complex Borosilicate And Hydroxide Of Aluminum Containing Iron And Magnesium And Calcium And Lithium And Sodium",
"TRACE ELEMENT",    "An Element That Occurs At Very Small Quantities In The Body But Is Nonetheless Important For Many Biological Processes ",
"TRACING PAPER",    "A Semitransparent Paper That Is Used For Tracing Drawings ",
"TRAGACANTH",   "A Gum Used In Pharmacy, Adhesives, And Textile Printing ",
"TRANSAMINASE", "A Class Of Transferases That Catalyze Transamination That Transfer An Amino Group From An Amino Acid To Another Compound ",
"TRANSFERASE",  "Any Of Various Enzymes That Move A Chemical Group From One Compound To Another Compound ",
"TRANSFER PAPER",   "A Paper That Is Coated With A Preparation For Transferring A Design To Another Surface ",
"TRANSFERRIN",  "A Globulin In Blood Plasma That Carries Iron ",
"TRANSPARENT GEM",  "A Gemstone Having The Property Of Transmitting Light Without Serious Diffusion ",
"TRANSPARENT SUBSTANCE",    "A Material Having The Property Of Admitting Light Diffusely",
"TRIAMCINOLONE",    "A Synthetic Corticosteroid Trade Names Aristocort Or Aristopak Or Kenalog Used As An Anti-Inflammatory Agent ",
"TRIAZINE", "Any Of Three Isomeric Compounds Having Three Carbon And Three Nitrogen Atoms In A Six-Membered Ring ",
"TRI-CHAD", "A Chad That Is Incompletely Removed And Still Attached At Three Corners ",
"TRICHLOROACETIC ACID", "A Strong Acid Made By Chlorinating Acetic Acid ",
"MARGARIN", "A Glyceryl Ester Of Margaric Acid ",
"TRIDYMITE",    "A Mineral Form Of Silica ",
"TRIOLEIN", "A Naturally Occurring Glyceride Of Oleic Acid That Is Found In Fats And Oils ",
"TRIMER",   "A Polymer Or A Molecule Of A Polymer Consisting Of Three Identical Monomers ",
"TRIOXIDE", "An Oxide Containing Three Atoms Of Oxygen In The Molecule ",
"TRIPALMITIN",  "A Triglyceride Of Palmitic Acid ",
"TRIPHOSPHOPYRIDINE",   "A Pyridine Ring With Three Phosphorus Groups ",
"TRIPHOSPHOPYRIDINE NUCLEOTIDE",    "A Coenzyme Of Several Enzymes ",
"TRIPHOSPHORIC ACID",   "An Acid That Is A Partial Anhydride Of Three Molecules Of Phosphoric Acid",
"TRISACCHARIDE",    "Any Of A Variety Of Carbohydrates That Yield Three Monosaccharide Molecules On Complete Hydrolysis ",
"TRISODIUM PHOSPHATE",  "The Tertiary Phosphate Of Sodium Used As A Builder In Soaps And Detergents ",
"TRISTEARIN",   "A Triglyceride Of Stearic Acid ",
"TRYPSIN",  "An Enzyme Of Pancreatic Origin",
"TRYPSINOGEN",  "Inactive Precursor Of Trypsin",
"TRYPTOPHAN",   "An Amino Acid That Occurs In Proteins",
"TUNA OIL", "An Oil Obtained From Tuna ",
"TUNDRA SOIL",  "A Black Mucky Soil With A Frozen Subsoil That Is Characteristic Of Arctic And Subarctic Regions ",
"TUNGSTEN STEEL",   "A Very Hard Heat-Resistant Steel Containing Tungsten ",
"TUNGSTATE",    "A Salt Of Tungstic Acid ",
"TUNGSTIC ACID",    "An Oxyacid Of Tungsten Often Polymeric In Nature Formed By Neutralizing Alkaline Tungstate Solutions ",
"TURQUOISE",    "A Blue To Grey Green Mineral Consisting Of Copper Aluminum Phosphate",
"TYPEWRITER PAPER", "Writing Paper Suitable For Use In A Typewriter ",
"TYRAMINE", "Amino Acid Derived From Tyrosine",
"TYROSINE", "An Amino Acid Found In Most Proteins",
"UBIQUINONE",   "Any Of Several Quinones Found In Living Cells And That Function As Coenzymes That Transfer Electrons From One Molecule To Another In Cell Respiration ",
"ULTRAMARINE",  "Blue Pigment Made Of Powdered Lapis Lazuli ",
"FRENCH BLUE",  "Ultramarine Pigment Prepared Artificially ",
"UMBER",    "An Earth Pigment ",
"RAW UMBER",    "Greenish Brown Pigment ",
"BURNT UMBER",  "Dark Brown Pigment Obtained By Heating Umber ",
"UNDECYLENIC ACID", "An Acid That Is A Component Of Perspiration ",
"UNLEADED GASOLINE",    "Gasoline That Has Not Been Treated With A Lead Compound ",
"UNDERCUT", "The Material Removed By A Cut Made Underneath ",
"UREASE",   "An Enzyme That Catalyzes The Hydrolysis Of Urea Into Carbon Dioxide And Ammonia",
"URETHANE", "An Ester Of Carbamic Acid ",
"URACIL",   "A Base Containing Nitrogen That Is Found In Rna But Not In Dna And Derived From Pyrimidine",
"URANINITE",    "A Mineral Consisting Of Uranium Oxide And Trace Amounts Of Radium And Thorium And Polonium And Lead And Helium",
"URANIUM ORE",  "Any Ore From Which Uranium Can Be Extracted ",
"URANYL",   "The Bivalent Radical Uo2 Which Forms Salts With Acids ",
"URANYL NITRATE",   "A Yellow Salt Obtained By The Reaction Of Uranium Salts With Nitric Acid ",
"URANYL OXALATE",   "A Salt Obtained By The Reaction Of Uranium Salts With Oxalic Acid ",
"UREA", "The Chief Solid Component Of Mammalian Urine",
"URIC ACID",    "A White Tasteless Odorless Crystalline Product Of Protein Metabolism",
"URATE",    "A Salt Of Uric Acid ",
"TOPHUS",   "A Deposit Of Urates Around A Joint Or In The External Ear",
"VALINE",   "An Essential Amino Acid Found In Proteins",
"LINSEED",  "The Seed Of Flax Used As A Source Of Oil ",
"LINSEED OIL",  "A Drying Oil Extracted From Flax Seed And Used In Making Such Things As Oil Paints ",
"TUNG OIL", "A Yellow Oil Obtained From The Seeds Of The Tung Tree ",
"CHAULMOOGRA OIL",  "An Oil From Chaulmoogra Trees",
"VANADATE", "A Salt Or Ester Of Vanadic Acid",
"VANADINITE",   "A Mineral Consisting Of Chloride And Vanadate Of Lead",
"VANADIUM PENTOXIDE",   "Any Of Various Oxyacids Of Vanadium",
"VANADIUM STEEL",   "Steel Alloyed With Vanadium For Greater Strength And High-Temperature Stability ",
"VERMICULITE",  "Any Of A Group Of Yellow Or Brown Hydrous Silicate Minerals Having A Micaceous Structure  ",
"VERY LOW DENSITY LIPOPROTEIN", "Large Lipoproteins Rich In Triglycerides",
"VESUVIANITE",  "A Green Or Yellow Or Brown Mineral Consisting Of A Hydrated Silicate",
"VINEGAR",  "Dilute Acetic Acid ",
"VINYL",    "Shiny And Tough And Flexible Plastic",
"VINYL POLYMER",    "A Thermoplastic Derived By Polymerization From Compounds Containing The Vinyl Group ",
"IODOPSIN", "A Violet Photopigment In The Retinal Cones Of The Eyes Of Most Vertebrates",
"VISUAL PURPLE",    "A Red Photopigment In The Retinal Rods Of Vertebrates",
"PHOTOPIGMENT", "A Special Pigment Found In The Rods And Cones Of The Retina ",
"VITAMIN",  "Any Of A Group Of Organic Substances Essential In Small Quantities To Normal Metabolism ",
"FAT-SOLUBLE VITAMIN",  "Any Vitamin That Is Soluble In Fats ",
"WATER-SOLUBLE VITAMIN",    "Any Vitamin That Is Soluble In Water ",
"VITAMIN A",    "Any Of Several Fat-Soluble Vitamins Essential For Normal Vision",
"PROVITAMIN",   "Vitamin Precursor",
"PROVITAMIN A", "An Orange Isomer Of An Unsaturated Hydrocarbon Found In Many Plants",
"B-COMPLEX VITAMIN",    "Originally Thought To Be A Single Vitamin But Now Separated Into Several B Vitamins ",
"VITAMIN B",    "A B Vitamin That Prevents Beriberi",
"VITAMIN BC",   "A B Vitamin That Is Essential For Cell Growth And Reproduction ",
"NIACIN",   "A B Vitamin Essential For The Normal Function Of The Nervous System And The Gastrointestinal Tract ",
"VITAMIN D",    "A Fat-Soluble Vitamin That Prevents Rickets ",
"VITAMIN E",    "A Fat-Soluble Vitamin That Is Essential For Normal Reproduction",
"BIOTIN",   "A B Vitamin That Aids In Body Growth ",
"VITAMIN K",    "A Fat-Soluble Vitamin That Helps In The Clotting Of Blood ",
"VITAMIN K",    "A Form Of Vitamin K ",
"VITAMIN P",    "A Vitamin That Maintains The Resistance Of Cell And Capillary Walls To Permeation ",
"VITAMIN C",    "A Vitamin Found In Fresh Fruits Especially Citrus Fruits And Vegetables",
"VITRIOL",  "H2So4 A Highly Corrosive Acid Made From Sulfur Dioxide",
"VOLATILE", "A Volatile Substance",
"WALLPAPER",    "A Decorative Paper For The Walls Of Rooms ",
"WASTE PAPER",  "Paper Discarded After Use ",
"WATER OF CRYSTALLIZATION", "The Water Present In Hydrated Compounds ",
"WAX",  "Any Of Various Substances Of Either Mineral Origin Or Plant Or Animal Origin",
"BEESWAX",  "A Yellow To Brown Wax Secreted By Honeybees To Build Honeycombs ",
"GHEDDA WAX",   "Wax From Indian And African Bees ",
"CERUMEN",  "A Soft Yellow Wax Secreted By Glands In The Ear Canal ",
"SPERMACETI",   "A White Waxy Substance From Oil Of The Sperm Whale ",
"VEGETABLE WAX",    "A Waxy Substance Obtained From Plants Especially From The Trunks Of Certain Palms ",
"SHELLAC WAX",  "A Hard Wax Separated From Shellac By Its Insolubility In Alcohol ",
"CADAVERINE",   "A Colorless Toxic Ptomaine With An Unpleasant Odor Formed During The Putrefaction Of Animal Tissue ",
"CADMIUM SULFIDE",  "A Yellow Sulfide Used Chiefly As A Pigment ",
"CADMIUM YELLOW",   "Pigment Of Cadmium Sulfide And Barium Sulfate Varying In Hue From Lemon Yellow To Orange ",
"CADMIUM YELLOW PALE",  "Pale-Hued Cadmium Yellow Pigment ",
"CADMIUM ORANGE",   "Orange-Hued Cadmium Yellow Pigment ",
"ZINC CADMIUM SULFIDE", "Cadmium Sulfide Containing Zinc ",
"VERDIGRIS",    "A Blue Or Green Powder Used As A Paint Pigment ",
"WAX PAPER",    "Paper That Has Been Waterproofed By Treatment With Wax Or Paraffin ",
"WETTING AGENT",    "A Chemical Agent Capable Of Reducing The Surface Tension Of A Liquid In Which It Is Dissolved ",
"DETERGENT",    "A Surface-Active Chemical Widely Used In Industry And Laundering ",
"BUILDER",  "A Substance Added To Soaps Or Detergents To Increase Their Cleansing Action ",
"WHALE OIL",    "A White To Brown Oil Obtained From Whale Blubber",
"WHEY", "The Serum Or Watery Part Of Milk That Is Separated From The Curd In Making Cheese ",
"WHITE LEAD",   "A Poisonous White Pigment That Contains Lead ",
"WICKER",   "Slender Flexible Branches Or Twigs Especially Of Willow Or Some Canes",
"WIESENBODEN",  "A Dark Meadow Soil Rich In Organic Material",
"WOOD", "The Hard Fibrous Lignified Substance Under The Bark Of Trees ",
"DYEWOOD",  "Any Wood From Which Dye Is Obtained ",
"HARDWOOD", "The Wood Of Broad-Leaved Dicotyledonous Trees As Distinguished From The Wood Of Conifers ",
"SOFTWOOD", "Wood That Is Easy To Saw From Conifers Such As Pine Or Fir ",
"PULPWOOD", "Softwood Used To Make Paper ",
"RAW WOOD", "Wood That Is Not Finished Or Painted ",
"HARDTACK", "A Mountain Mahogany ",
"FIREWOOD", "Wood Used For Fuel",
"CORDWOOD", "Firewood Cut And Stacked In Cords",
"BACKLOG",  "The Large Log At The Back Of A Hearth Fire ",
"YULE LOG", "Large Log Traditionally Burned At Christmas ",
"BRAND",    "A Piece Of Wood That Has Been Burned Or Is Burning ",
"PINE KNOT",    "A Joint Of Pine Wood Used For Fuel ",
"IGNITER",  "A Substance Used To Ignite Or Kindle A Fire ",
"KINDLING", "Material For Starting A Fire ",
"PUNK", "Substance That Smolders When Ignited",
"BOARD",    "A Stout Length Of Sawn Timber",
"LEMONGRASS",   "An Aromatic Oil That Smells Like Lemon And Is Widely Used In Asian Cooking And In Perfumes And Medicines ",
"PLANKING", "Planks Collectively",
"CHIPBOARD",    "A Cheap Hard Material Made From Wood Chips That Are Pressed Together And Bound With Synthetic Resin ",
"DEAL", "A Plank Of Softwood Fir Or Pine Board ",
"KNOT", "A Hard Cross-Grained Round Piece Of Wood In A Board Where A Branch Emerged",
"KNOTHOLE", "A Hole In A Board Where A Knot Came Out ",
"CLAPBOARD",    "A Long Thin Board With One Edge Thicker Than The Other",
"WOLFRAMITE",   "A Mineral Consisting Of Iron And Manganese Tungstate In Crystalline Form",
"WOLLASTONITE", "A White Or Greyish Mineral Typically Found In Metamorphic Limestone",
"WOOD PULP",    "Wood That Has Been Ground To A Pulp",
"WOOD SUGAR",   "A Sugar Extracted From Wood Or Straw",
"WOOD'S METAL", "A Fusible Alloy That Is Half Bismuth Plus Lead, Tin, And Cadmium",
"WOOD TAR", "Any Tar Obtained By The Destructive Distillation Of Wood ",
"WOOL", "Fiber Sheared From Animals Such As Sheep And Twisted Into Yarn For Weaving ",
"RAW WOOL", "Wool In Its Natural Condition",
"ALPACA",   "Wool Of The Alpaca ",
"CASHMERE", "The Wool Of The Kashmir Goat ",
"FLEECE",   "The Wool Of A Sheep Or Similar Animal ",
"SHODDY",   "Reclaimed Wool Fiber ",
"VICUNA",   "The Wool Of The Vicuna ",
"VIRGIN WOOL",  "Wool Not Used Before",
"WRAPPING PAPER",   "A Tough Paper Used For Wrapping ",
"WRITING PAPER",    "Paper Material Made Into Thin Sheets That Are Sized To Take Ink",
"WOOL OIL", "Any Oil Used To Oil Wool Before Spinning ",
"WULFENITE",    "A Yellow To Orange Or Brown Mineral Used As A Molybdenum Ore ",
"WURTZITE", "A Brownish-Black Mineral Consisting Of Zinc Sulfide ",
"XENOTIME", "A Brown-To-Yellow Mineral That Is A Phosphate Of Yttrium In Crystalline Form ",
"XYLENE",   "A Colorless Flammable Volatile Liquid Hydrocarbon Used As A Solvent ",
"YEAST",    "A Commercial Leavening Agent Containing Yeast Cells",
"YELLOWCAKE",   "An Impure Mixture Of Uranium Oxides Obtained During The Processing Of Uranium Ore ",
"MOTHER",   "A Stringy Slimy Substance Consisting Of Yeast Cells And Bacteria",
"ZEOLITE",  "Any Of A Family Of Glassy Minerals Analogous To Feldspar Containing Hydrated Aluminum Silicates Of Calcium Or Sodium Or Potassium",
"CHABAZITE",    "A Group Of Minerals Of The Zeolite Family Consisting Of A Hydrous Silicate Of Calcium And Aluminum ",
"HEULANDITE",   "A Group Of Minerals Of The Zeolite Family Consisting Of A Hydrous Aluminum Silicate Of Sodium And Calcium ",
"NATROLITE",    "A Group Of Minerals Of The Zeolite Family Consisting Of A Hydrous Silicate Of Sodium And Aluminum ",
"PHILLIPSITE",  "A Group Of White Or Reddish Crystalline Minerals Of The Zeolite Family Consisting Of A Hydrous Silicate Of Calcium And Potassium And Aluminum ",
"ZINC BLENDE",  "An Ore That Is The Chief Source Of Zinc",
"ZINC OXIDE",   "Oxide Of Zinc",
"ZINC SULFATE", "A Colorless Water-Soluble Powder",
"ZINC SULFIDE", "A Yellow To White Crystalline Fluorescent Compound That Occurs Naturally As Sphalerite Or Wurtzite And Is Used As A Luminous Pigment ",
"ZINC WHITE",   "A White Pigment Used In House Paints",
"ZINKENITE",    "A Steel Grey Metallic Mineral A Sulphide Of Lead And Antimony ",
"ZINNWALDITE",  "A Mica Containing Iron And Lithium ",
"ZIRCON",   "A Common Mineral Occurring In Small Crystals",
"ZIRCONIUM OXIDE",  "A White Crystalline Oxide",
"ZYMASE",   "A Complex Of Enzymes That Cause Glycolysis",
"EMANATION",    "Something That Is Emitted Or Radiated As A Gas Or An Odor Or A Light, Etc. ",
"ECTOPLASM",    "Spiritualism A Substance Supposed To Emanate From The Body Of The Medium During A Trance ",
"ESSENCE",  "Any Substance Possessing To A High Degree The Predominant Properties Of A Plant Or Drug Or Other Natural Product From Which It Is Extracted ",
"LIGAND",   "A Substance An Atom Or Molecule Or Radical Or Ion That Forms A Complex Around A Central Atom ",
"ENAMEL",   "A Colored Glassy Compound Opaque Or Partially Opaque That Is Fused To The Surface Of Metal Or Glass Or Pottery For Decoration Or Protection ",
"IMIDE",    "Any Of A Class Of Organic Compounds That Contain The Divalent Radical -Conhco- ",
"METABOLITE",   "Any Substance Involved In Metabolism Either As A Product Of Metabolism Or As Necessary For Metabolism ",
"VEGETABLE MATTER", "Matter Produced By Plants Or Growing In The Manner Of A Plant ",
"ANABOLIC STEROID", "Any Of A Group Of Synthetic Steroid Hormones Used To Stimulate Muscle And Bone Growth",
"PREGNANEDIOL", "A Compound Found In Women'S Urine During Certain Phases Of The Menstrual Cycle And In The Urine Of Pregnant Women ",
"TUBOCURARINE", "A Toxic Alkaloid Found In Certain Tropical South American Trees That Is A Powerful Relaxant For Striated Muscles",
"TUBERCULIN",   "A Sterile Liquid Containing A Purified Protein Derivative Of The Tuberculosis Bacterium",
"VEHICLE",  "Any Substance That Facilitates The Use Of A Drug Or Pigment Or Other Material That Is Mixed With It ",
"VESICANT", "A Chemical Agent That Causes Blistering Especially Mustard Gas ",
"VERNIX",   "A White Cheeselike Protective Material That Covers The Skin Of A Fetus ",
"VITRIFICATION",    "A Vitrified Substance",
"WAD",  "A Small Mass Of Soft Material",
"XANTHATE", "A Salt Or Ester Of Xanthic Acid ",
"XANTHIC ACID", "Any Of A Class Of Unstable Organic Acids Containing Sulphur ",
"XANTHINE", "Crystalline Oxidation Product Of The Metabolism Of Nucleoproteins",
"TIME PERIOD",  "An Amount Of Time",
"TRIAL PERIOD", "A Period Of Time During Which Someone Or Something Is Tested ",
"TIME FRAME",   "A Time Period During Which Something Occurs Or Is Expected To Occur",
"GEOLOGICAL TIME",  "The Time Of The Physical Formation And Development Of The Earth Especially Prior To Human History ",
"BIOLOGICAL TIME",  "The Time Of Various Biological Processes ",
"COSMIC TIME",  "The Time Covered By The Physical Formation And Development Of The Universe ",
"CIVIL TIME",   "The Official Time In A Local Region Adjusted For Location Around The Earth",
"DAYLIGHT-SAVING TIME", "Time During Which Clocks Are Set One Hour Ahead Of Local Standard Time",
"GRACE",    "A Period Of Time Past The Deadline For Fulfilling An Obligation During Which A Penalty That Would Be Imposed For Being Late Is Waived, Especially An Extended Period Granted As A Special Favor",
"HOURS",    "An Indefinite Period Of Time",
"DOWNTIME", "A Period Of Time When Something As A Machine Or Factory Is Not Operating Especially As A Result Of Malfunctions ",
"UPTIME",   "A Period Of Time When Something As A Machine Or Factory Is Functioning And Available For Use ",
"WORK TIME",    "A Time Period When You Are Required To Work ",
"TIME OFF", "A Time Period When You Are Not Required To Work",
"FACE TIME",    "Work Time Spent At The Location Of Or In The Presence Of Other People",
"COMPENSATORY TIME",    "Time Off That Is Granted To A Worker As Compensation For Working Overtime ",
"BOUT", "A Period Of Illness",
"HOSPITALIZATION",  "A Period Of Time When You Are Confined To A Hospital",
"TRAVEL TIME",  "A Period Of Time Spent Traveling",
"PRESENT",  "The Period Of Time That Is Happening Now",
"NOW",  "The Momentary Present",
"HERE AND NOW", "At This Time",
"DATE", "The Present",
"TIMES",    "A More Or Less Definite Period Of Time Now Or Previously Present",
"MODERN TIMES", "The Circumstances And Ideas Of The Present Age",
"ROMAN TIMES",  "The Time Period During Which Rome Dominated Europe ",
"PAST", "The Time That Has Elapsed",
"YORE", "Time Long Past ",
"BYGONE",   "Past Events To Be Put Aside",
"OLD",  "Past Times Especially In The Phrase `In Days Of Old' ",
"HISTORY",  "The Aggregate Of Past Events",
"FUTURE",   "The Time Yet To Come ",
"KINGDOM COME", "The End Of Time",
"MUSICAL TIME", "Music The Beat Of Musical Rhythm ",
"TIME", "An Indefinite Period Usually Marked By Specific Attributes Or Activities",
"ELIZABETHAN AGE",  "A Period In British History During The Reign Of Elizabeth I In The 16Th Century",
"VICTORIAN AGE",    "A Period In British History During The Reign Of Queen Victoria In The 19Th Century",
"DAY",  "Some Point Or Period In Time",
"DEAD", "A Time When Coldness Or Some Other Quality Associated With Death Is Intense",
"HARD TIMES",   "A Time Of Difficulty ",
"INCARNATION",  "Time Passed In A Particular Bodily Form",
"CONTINUUM",    "A Continuous Nonspatial Whole Or Extent Or Succession In Which No Part Or Portion Is Distinct Or Distinguishable From Adjacent Parts ",
"HISTORY",  "The Continuum Of Events Occurring In Succession Leading From The Past To The Present And Even Into The Future",
"PHANEROZOIC",  "The Period From About 540 Million Years Ago Until The Present, A Period When Abundant Life Existed ",
"CENOZOIC", "Approximately The Last 63 Million Years ",
"QUATERNARY",   "Last 2 Million Years ",
"HOLOCENE", "Approximately The Last 10,000 Years ",
"PLEISTOCENE",  "From Two Million To 11 Thousand Years Ago",
"TERTIARY", "From 63 Million To 2 Million Years Ago ",
"PLIOCENE", "From 13 Million To 2 Million Years Ago",
"MIOCENE",  "From 25 Million To 13 Million Years Ago",
"OLIGOCENE",    "From 40 Million To 25 Million Years Ago",
"EOCENE",   "From 58 Million To 40 Million Years Ago",
"PALEOCENE",    "From 63 Million To 58 Million Years Ago",
"MESOZOIC", "From 230 Million To 63 Million Years Ago ",
"CRETACEOUS",   "From 135 Million To 63 Million Years Ago",
"JURASSIC", "From 190 Million To 135 Million Years Ago",
"TRIASSIC", "From 230 Million To 190 Million Years Ago",
"PALEOZOIC",    "From 544 Million To About 230 Million Years Ago ",
"PERMIAN",  "From 280 Million To 230 Million Years Ago",
"CARBONIFEROUS",    "From 345 Million To 280 Million Years Ago ",
"PENNSYLVANIAN",    "From 310 Million To 280 Million Years Ago",
"MISSISSIPPIAN",    "From 345 Million To 310 Million Years Ago",
"DEVONIAN", "From 405 Million To 345 Million Years Ago",
"SILURIAN", "From 425 Million To 405 Million Years Ago",
"ORDOVICIAN",   "From 500 Million To 425 Million Years Ago",
"CAMBRIAN", "From 544 Million To About 500 Million Years Ago",
"PRECAMBRIAN",  "The Eon Following The Hadean Time And Preceding The Phanerozoic Eon",
"PROTEROZOIC",  "From 2,500 To 544 Million Years Ago",
"ARCHEAN",  "The Time From 3,800 Million Years To 2,500 Million Years Ago",
"HADEAN",   "The Earliest Eon In The History Of The Earth From The First Accretion Of Planetary Material Around 4,600 Million Years Ago Until The Date Of The Oldest Known Rocks About 3,800 Million Years Ago",
"CLOCK TIME",   "A Reading Of A Point In Time As Given By A Clock",
"GREENWICH MEAN TIME",  "The Local Time At The 0 Meridian Passing Through Greenwich, England",
"COORDINATED UNIVERSAL TIME",   "Greenwich Mean Time Updated With Leap Seconds ",
"EARTH-RECEIVED TIME",  "The Coordinated Universal Time When An Event Is Received On Earth ",
"ONE-WAY LIGHT TIME",   "The Elapsed Time It Takes For Light Or Radio Signals To Travel Between The Earth And A Celestial Object ",
"ROUND-TRIP LIGHT TIME",    "The Elapsed Time It Takes For A Signal To Travel From Earth To A Spacecraft Or Other Body And Back To The Starting Point ",
"ELAPSED TIME", "The Time That Elapses While Some Event Is Occurring ",
"TRANSMISSION TIME",    "The Coordinated Universal Time When A Transmission Is Sent From Earth To A Spacecraft Or Other Celestial Body ",
"SPACECRAFT EVENT TIME",    "The Coordinated Universal Time On Board The Spacecraft",
"SPACECRAFT CLOCK TIME",    "The Clock Time Given By A Clock Carried On Board A Spacecraft ",
"ATLANTIC TIME",    "Standard Time In The 4Th Time Zone West Of Greenwich, Reckoned At The 60Th Meridian",
"EASTERN TIME", "Standard Time In The 5Th Time Zone West Of Greenwich, Reckoned At The 75Th Meridian",
"CENTRAL TIME", "Standard Time In The 6Th Time Zone West Of Greenwich, Reckoned At The 90Th Meridian",
"MOUNTAIN TIME",    "Standard Time In The 7Th Time Zone West Of Greenwich, Reckoned At The 105Th Meridian West",
"PACIFIC TIME", "Standard Time In The 8Th Time Zone West Of Greenwich, Reckoned At The 120Th Meridian West",
"ALASKA STANDARD TIME", "Standard Time In The 9Th Time Zone West Of Greenwich, Reckoned At The 135Th Meridian West",
"HAWAII TIME",  "Standard Time In The 10Th Time Zone West Of Greenwich, Reckoned At The 150Th Meridian West",
"BERING TIME",  "Standard Time In The 11Th Time Zone West Of Greenwich, Reckoned At The 165Th Meridian West",
"DURATION", "The Property Of Enduring Or Continuing In Time ",
"CLOCKING", "The Time Taken To Traverse A Measured Course",
"LONGUEUR", "A Period Of Dullness Or Boredom Especially In A Work Of Literature Or Performing Art ",
"RESIDENCE TIME",   "The Period Of Time Spent In A Particular Place ",
"SPAN", "The Complete Duration Of Something",
"STRETCH",  "An Unbroken Period Of Time During Which You Do Something",
"TIME SCALE",   "An Arrangement Of Events Used As A Measure Of Duration",
"VALUE",    "Music The Relative Duration Of A Musical Note ",
"EXTENDED TIME SCALE",  "Simulation The Time Scale Used In Data Processing When The Time-Scale Factor Is Greater Than One ",
"FAST TIME SCALE",  "Simulation The Time Scale Used In Data Processing When The Time-Scale Factor Is Less Than One ",
"TIME BEING",   "The Present Occasion",
"BIOLOGICAL CLOCK", "An Innate Mechanism In Living Organisms That Controls The Periodicity Of Many Physiological Functions ",
"CIRCADIAN RHYTHM", "A Daily Cycle Of Activity Observed In Many Living Organisms ",
"FOURTH DIMENSION", "The Fourth Coordinate That Is Required Along With Three Spatial Dimensions To Specify A Physical Event ",
"WORKWEEK", "Hours Or Days Of Work In A Calendar Week",
"WEEK", "A Period Of Seven Consecutive Days Starting On Sunday ",
"MIDWEEK",  "The Middle Of A Week ",
"WORKDAY",  "The Amount Of Time That A Worker Must Work For An Agreed Daily Wage",
"WORKDAY",  "A Day On Which Work Is Done ",
"REST DAY", "A Day Set Aside For Rest ",
"OVERTIME", "Work Done In Addition To Regular Working Hours ",
"TURNAROUND",   "Time Need To Prepare A Vessel Or Ship For A Return Trip ",
"SPARE TIME",   "Time Available For Hobbies And Other Activities That You Enjoy ",
"DAY OFF",  "A Day When You Are Not Required To Work",
"LEISURE",  "Time Available For Ease And Relaxation",
"VACATION", "Leisure Time Away From Work Devoted To Rest Or Pleasure",
"HALF-TERM",    "A Short Vacation About Halfway Through A School Term",
"VAC",  "Informal Term For Vacation ",
"HALF-HOLIDAY", "A Day On Which Half Is Free From Work Or Duty ",
"PLAYTIME", "Time For Play Or Diversion ",
"FIELD DAY",    "A Day Devoted To An Outdoor Social Gathering ",
"HONEYMOON",    "A Holiday Taken By A Newly Married Couple ",
"PAID VACATION",    "A Vacation From Work By An Employee With Pay Granted ",
"LEAVE",    "The Period Of Time During Which You Are Absent From Work Or Duty",
"FURLOUGH", "A Temporary Leave Of Absence From Military Duty ",
"PASS", "Military A Written Leave Of Absence",
"COMPASSIONATE LEAVE",  "Military Leave Granted In An Emergency Such As Family Sickness Or Death ",
"SABBATICAL",   "A Leave Usually Taken Every Seventh Year ",
"SABBATICAL YEAR",  "A Sabbatical Leave Lasting One Year ",
"SHORE LEAVE",  "Leave Granted To A Sailor Or Naval Officer ",
"SICK LEAVE",   "A Leave Of Absence From Work Because Of Illness ",
"TERMINAL LEAVE",   "Final Leave Before Discharge From Military Service ",
"LIFE", "The Period During Which Something Is Functional As Between Birth And Death",
"LIFE", "The Period Between Birth And The Present Time",
"DAYS", "The Time During Which Someone'S Life Continues",
"MILLENNIUM",   "A Span Of 1000 Years ",
"BIMILLENNIUM", "A Span Of 2000 Years ",
"OCCUPATION",   "The Period Of Time During Which A Place Or Position Or Nation Is Occupied",
"PAST", "A Earlier Period In Someone'S Life Especially One That They Have Reason To Keep Secret",
"SHELF LIFE",   "The Length Of Time A Packaged Food Or Drug Will Last Without Deteriorating ",
"LIFE EXPECTANCY",  "An Expected Time To Live As Calculated On The Basis Of Statistical Probabilities ",
"BIRTH",    "The Time When Something Begins Especially Life",
"CRADLE",   "Birth Of A Person",
"PUERPERIUM",   "Time Period Following Childbirth When The Mother'S Uterus Shrinks And The Other Functional And Anatomic Changes Of Pregnancy Are Resolved",
"LACTATION",    "The Period Following Birth During Which Milk Is Secreted",
"INCIPIENCY",   "Beginning To Exist Or To Be Apparent",
"DEATH",    "The Time At Which Life Ends",
"GRAVE",    "Death Of A Person",
"AFTERLIFE",    "Life After Death ",
"IMMORTALITY",  "Perpetual Life After Death ",
"PERIOD",   "The End Or Completion Of Something",
"TIME OF LIFE", "A Period Of Time During Which A Person Is Normally In A Particular Life State ",
"SUMMER",   "The Period Of Finest Development, Happiness, Or Beauty",
"AGE",  "A Time Of Life Usually Defined In Years At Which Some Particular Qualification Or Power Arises",
"NEONATAL PERIOD",  "The First 28 Days Of Life ",
"INFANCY",  "The Early Stage Of Growth Or Development ",
"ANAL STAGE",   "Psychoanalysis The Second Sexual And Social Stage Of A Child'S Development During Which Bowel Control Is Learned ",
"GENITAL STAGE",    "Psychoanalysis The Fifth Sexual And Social Stage In A Person'S Development Occurring During Adolescence",
"LATENCY STAGE",    "Psychoanalysis The Fourth Period From About Age 5 Or 6 Until Puberty During Which Sexual Interests Are Supposed To Be Sublimated Into Other Activities ",
"ORAL STAGE",   "Psychoanalysis The First Sexual And Social Stage Of An Infant'S Development",
"PHALLIC STAGE",    "Psychoanalysis The Third Stage In A Child'S Development When Awareness Of And Manipulation Of The Genitals Is Supposed To Be A Primary Source Of Pleasure ",
"CHILDHOOD",    "The Time Of Person'S Life When They Are A Child ",
"GIRLHOOD", "The Childhood Of A Girl ",
"BOYHOOD",  "The Childhood Of A Boy ",
"SCHOOLDAYS",   "The Time Of Life When You Are Going To School ",
"YOUTH",    "The Time Of Life Between Childhood And Maturity ",
"ADOLESCENCE",  "The Time Period Between The Beginning Of Puberty And Adulthood ",
"PREPUBERTY",   "A Period Of Two Years Immediately Prior To The Onset Of Puberty When Growth And Changes Leading To Sexual Maturity Occur ",
"PUBERTY",  "The Time Of Life When Sex Glands Become Functional ",
"TEENS",    "The Time Of Life Between The Ages Of 12 And 20 ",
"TWENTIES", "The Time Of Life Between 20 And 30 ",
"THIRTIES", "The Time Of Life Between 30 And 40 ",
"FORTIES",  "The Time Of Life Between 40 And 50 ",
"FIFTIES",  "The Time Of Life Between 50 And 60 ",
"SIXTIES",  "The Time Of Life Between 60 And 70 ",
"GOLDEN YEARS", "The Time Of Life After Retirement From Active Work ",
"SEVENTIES",    "The Time Of Life Between 70 And 80 ",
"EIGHTIES", "The Time Of Life Between 80 And 90 ",
"NINETIES", "The Time Of Life Between 90 And 100 ",
"BLOOM",    "The Best Time Of Youth ",
"AGE OF CONSENT",   "The Minimum Age For Marrying Without Parental Consent Or The Minimum Age For Consensual Sexual Relations",
"MAJORITY", "The Age At Which Persons Are Considered Competent To Manage Their Own Affairs ",
"MINORITY", "Any Age Prior To The Legal Age ",
"PRIME",    "The Time Of Maturity When Power And Vigor Are Greatest ",
"DRINKING AGE", "The Age At Which Is Legal For A Person To Buy Alcoholic Beverages ",
"VOTING AGE",   "The Age At Which A Person Is Old Enough To Vote In Public Elections ",
"ADULTHOOD",    "The Period Of Time In Your Life After Your Physical Growth Has Stopped And You Are Fully Developed ",
"MATURITY", "The Date On Which An Obligation Must Be Repaid ",
"BACHELORHOOD", "The Time Of A Man'S Life Prior To Marriage ",
"MIDDLE AGE",   "The Time Of Life Between Youth And Old Age E.G., Between 40 And 60 Years Of Age ",
"WIDOWHOOD",    "The Time Of A Woman'S Life When She Is A Widow ",
"OLD AGE",  "A Late Time Of Life",
"DOTAGE",   "Mental Infirmity As A Consequence Of Old Age",
"DEATHBED", "The Last Few Hours Before Death ",
"MENOPAUSE",    "The Time In A Woman'S Life In Which The Menstrual Cycle Ends ",
"CLIMACTERIC",  "A Period In A Man'S Life Corresponding To Menopause ",
"TIME UNIT",    "A Unit For Measuring Time Periods ",
"DAY",  "Time For Earth To Make A Complete Rotation On Its Axis",
"NIGHT",    "The Dark Part Of The Diurnal Cycle Considered A Time Unit",
"TOMORROW", "The Day After Today",
"TODAY",    "The Day That Includes The Present Moment As Opposed To Yesterday Or Tomorrow",
"YESTERDAY",    "The Day Immediately Before Today",
"MORROW",   "The Next Day",
"EVE",  "The Day Before",
"MEAN TIME",    "Astronomy Time Based On The Motion Of The Mean Sun An Imaginary Sun Moving Uniformly Along The Celestial Equator ",
"TERRESTRIAL TIME", "Astronomy A Measure Of Time Defined By Earth'S Orbital Motion",
"CALENDAR DAY", "A Day Reckoned From Midnight To Midnight ",
"ADMISSION DAY",    "In Some States Of The United States: A Legal Holiday Commemorating The Day The State Was Admitted To The Union ",
"ARBOR DAY",    "A Day Designated For Planting Trees ",
"CINCO DE MAYO",    "The Fifth Of May Which Is Observed In Mexico And Mexican-American Communities In The United States To Commemorate The Mexican Victory Over The French In The Battle Of Puebla In 1862 ",
"COMMENCEMENT DAY", "The Day On Which University Degrees Are Conferred ",
"NOVEMBER", "Anniversary Of The Discovery Of The Gunpowder Plot ",
"GUY FAWKES DAY",   "Day For The Celebration Of The Discovery Of The Gunpowder Plot ",
"BONFIRE NIGHT",    "Effigies Of Guy Fawkes Are Burned On This Night ",
"INAUGURATION DAY", "The Day Designated For Inauguration Of The United States President ",
"LEAP DAY", "The Name Of The Day That Is Added During A Leap Year ",
"DATE", "The Specified Day Of The Month",
"FUTURE DATE",  "A Particular Day In The Future That Is Specified As The Time Something Will Happen ",
"RAIN DATE",    "An Alternative Date Set For Some Outdoor Event In Case It Rains On The Appointed Date",
"SELL-BY DATE", "A Date Stamped On Perishable Produce Indicating The Date By Which It Should Be Sold ",
"QUARTER DAY",  "A Christian Holy Day",
"FAST DAY", "A Day Designated For Fasting ",
"MAJOR FAST DAY",   "One Of Two Major Fast Days On The Jewish Calendar ",
"MINOR FAST DAY",   "One Of Five Minor Fast Days On The Jewish Calendar ",
"FEAST DAY",    "A Day Designated For Feasting ",
"SUCCOTH",  "A Major Jewish Festival Beginning On The Eve Of The 15Th Of Tishri And Commemorating The Shelter Of The Israelites During Their 40 Years In The Wilderness ",
"RELIGIOUS FESTIVAL",   "A Festival Having Religious Significance ",
"FESTIVAL", "A Day Or Period Of Time Set Aside For Feasting And Celebration ",
"D-DAY",    "Date Of The Allied Landing In France, World War Ii ",
"V-DAY",    "The Day Of A Victory ",
"V-E DAY",  "The Date Of Allied Victory In Europe, World War Ii ",
"V-J DAY",  "The Date Of Allied Victory Over Japan, World War Ii ",
"DAY OF THE WEEK",  "Any One Of The Seven Days In A Week ",
"WEEKDAY",  "Any Day Except Sunday And Sometimes Except Saturday ",
"FERIA",    "A Weekday On Which No Festival Or Holiday Is Celebrated",
"SUNDAY",   "First Day Of The Week",
"MONDAY",   "The Second Day Of The Week",
"TUESDAY",  "The Third Day Of The Week",
"WEDNESDAY",    "The Fourth Day Of The Week",
"THURSDAY", "The Fifth Day Of The Week",
"FRIDAY",   "The Sixth Day Of The Week",
"SATURDAY", "The Seventh And Last Day Of The Week",
"SABBATH",  "A Day Of Rest And Worship: Sunday For Most Christians",
"MORNING",  "The Time Period Between Dawn And Noon",
"NOON", "The Middle Of The Day ",
"MEALTIME", "The Hour At Which A Meal Is Habitually Or Customarily Eaten ",
"BREAKFAST TIME",   "The Customary Or Habitual Hour For Eating Breakfast ",
"LUNCHTIME",    "The Customary Or Habitual Hour For Eating Lunch",
"DINNERTIME",   "The Customary Or Habitual Hour For The Evening Meal ",
"AFTERNOON",    "The Part Of The Day Between Noon And Evening",
"MIDAFTERNOON", "The Middle Part Of The Afternoon ",
"EVENING",  "The Latter Part Of The Day The Period Of Decreasing Daylight From Late Afternoon Until Nightfall",
"GUEST NIGHT",  "An Evening When Members Of A Club Or College Can Bring Their Friends As Guests ",
"PRIME TIME",   "The Hours Between 7 And 11 P.M. When The Largest Tv Audience Is Available ",
"NIGHT",    "The Time After Sunset And Before Sunrise While It Is Dark Outside ",
"WEEKNIGHT",    "Any Night Of The Week Except Saturday Or Sunday ",
"LATE-NIGHT HOUR",  "The Latter Part Of Night ",
"MIDNIGHT", "12 O'Clock At Night",
"SMALL HOURS",  "The Hours Just After Midnight ",
"BEDTIME",  "The Time You Go To Bed ",
"LIGHTS-OUT",   "A Prescribed Bedtime ",
"CLOSING TIME", "The Regular Time Of Day When An Establishment Closes To The Public ",
"DAWN", "The First Light Of Day",
"EARLY-MORNING HOUR",   "An Hour Early In The Morning ",
"SUNSET",   "The Time In The Evening At Which The Sun Begins To Fall Below The Horizon ",
"TWILIGHT", "The Time Of Day Immediately Following Sunset",
"WEEK", "Any Period Of Seven Consecutive Days",
"WEEK FROM MONDAY", "A Time Period Of A Week Or More",
"FORTNIGHT",    "A Period Of Fourteen Consecutive Days",
"WEEKEND",  "A Time Period Usually Extending From Friday Night Through Sunday",
"RAG",  "A Week At British Universities During Which Side-Shows And Processions Of Floats Are Organized To Raise Money For Charities ",
"RAG DAY",  "A Day On Which University Students Hold A Rag ",
"RED-LETTER DAY",   "A Memorably Happy Or Noteworthy Day From The Custom Of Marking Holy Days In Red On Church Calendars ",
"JUDGMENT DAY", "New Testament Day At The End Of Time Following Armageddon When God Will Decree The Fates Of All Individual Humans According To The Good And Evil Of Their Earthly Lives ",
"OFF-DAY",  "A Day When Things Go Poorly",
"ACCESS TIME",  "Computer Science The Interval Between The Time Data Is Requested By The System And The Time The Data Is Provided By The Drive",
"DISTANCE", "The Interval Between Two Times",
"EMBOLISM", "An Insertion Into A Calendar ",
"PAYDAY",   "The Day On Which You Receive Pay For Your Work ",
"POLLING DAY",  "The Day Appointed For An Election",
"CHURCH YEAR",  "The Year In The Ecclesiastical Calendar",
"CALENDAR", "A System Of Timekeeping That Defines The Beginning And Length And Divisions Of The Year ",
"TIMEKEEPING",  "The Act Or Process Of Determining The Time ",
"ROMAN CALENDAR",   "The Lunar Calendar In Use In Ancient Rome",
"IDES", "In The Roman Calendar: The 15Th Of March Or May Or July Or October Or The 13Th Of Any Other Month ",
"MARKET DAY",   "A Fixed Day For Holding A Public Market ",
"GREGORIAN CALENDAR",   "The Solar Calendar Now In General Use, Introduced By Gregory Xiii In 1582 To Correct An Error In The Julian Calendar By Suppressing 10 Days, Making Oct 5 Be Called Oct 15, And Providing That Only Centenary Years Divisible By 400 Should Be Leap Years",
"JULIAN CALENDAR",  "The Solar Calendar Introduced In Rome In 46 B.C. By Julius Caesar And Slightly Modified By Augustus, Establishing The 12-Month Year Of 365 Days With Each 4Th Year Having 366 Days And The Months Having 31 Or 30 Days Except For February ",
"REVOLUTIONARY CALENDAR",   "The Calendar Adopted By The First French Republic In 1793 And Abandoned In 1805",
"REVOLUTIONARY CALENDAR MONTH", "A Month In The Revolutionary Calendar ",
"VENDEMIAIRE",  "First Month Of The Revolutionary Calendar September And October",
"BRUMAIRE", "Second Month Of The Revolutionary Calendar October And November",
"FRIMAIRE", "Third Month Of The Revolutionary Calendar November And December",
"NIVOSE",   "Fourth Month Of The Revolutionary Calendar December And January",
"PLUVIOSE", "Fifth Month Of The Revolutionary Calendar January And February",
"VENTOSE",  "Sixth Month Of The Revolutionary Calendar February And March",
"GERMINAL", "Seventh Month Of The Revolutionary Calendar March And April",
"FLOREAL",  "Eighth Month Of The Revolutionary Calendar April And May",
"PRAIRIAL", "Ninth Month Of The Revolutionary Calendar May And June",
"MESSIDOR", "Tenth Month Of The Revolutionary Calendar June And July",
"THERMIDOR",    "Eleventh Month Of The Revolutionary Calendar July And August",
"FRUCTIDOR",    "Twelfth Month Of The Revolutionary Calendar August And September",
"JEWISH CALENDAR",  "Judaism The Calendar Used By The Jews",
"LUNAR CALENDAR",   "A Calendar Based On Lunar Cycles ",
"LUNISOLAR CALENDAR",   "A Calendar Based On Both Lunar And Solar Cycles ",
"SOLAR CALENDAR",   "A Calendar Based On Solar Cycles ",
"ISLAMIC CALENDAR", "The Lunar Calendar Used By Muslims",
"HINDU CALENDAR",   "The Lunisolar Calendar Governing The Religious Life Of Hindus",
"DEADLINE", "The Point In Time At Which Something Must Be Completed ",
"CURFEW",   "The Time That The Curfew Signal Is Sounded ",
"ANACHRONISM",  "Something Located At A Time When It Could Not Have Existed Or Occurred ",
"POINT",    "An Instant Of Time",
"ARRIVAL TIME", "The Time At Which A Public Conveyance Is Scheduled To Arrive At A Given Destination ",
"DEPARTURE TIME",   "The Time At Which A Public Conveyance Is Scheduled To Depart From A Given Point Of Origin ",
"CHECKOUT", "The Latest Time For Vacating A Hotel Room",
"HOLY WEEK",    "The Week Before Easter ",
"HOLY YEAR",    "Roman Catholic Church A Period Of Remission From Sin Usually Granted Every 25 Years ",
"CHURCH CALENDAR",  "A Calendar Of The Christian Year Indicating The Dates Of Fasts And Festivals ",
"WALPURGIS NIGHT",  "Eve Of May Day ",
"NEW YEAR'S EVE",   "The Last Day Of The Year ",
"NEW YEAR'S DAY",   "The First Day Of The Year ",
"NEW YEAR", "The Calendar Year Just Begun ",
"MARTIN LUTHER KING JR'S BIRTHDAY", "Observed On The Monday Closest To January 15 ",
"ROBERT E LEE'S BIRTHDAY",  "Celebrated In Southern United States ",
"HOGMANAY", "New Year'S Eve In Scotland ",
"ROSH HASHANAH",    "Judaism A Solemn Jewish Feast Day Celebrated On The 1St Or 1St And 2Nd Of Tishri",
"ROSH HODESH",  "Judaism The Beginning Of Each Month In The Jewish Calendar",
"TET",  "The New Year In Vietnam",
"HOLIDAY",  "A Day On Which Work Is Suspended By Law Or Custom",
"RELIGIOUS HOLIDAY",    "A Day Specified For Religious Observance ",
"HIGH HOLY DAY",    "Jewish Holy Days Observed With Particular Solemnity ",
"CHRISTIAN HOLY DAY",   "A Religious Holiday For Christians ",
"JEWISH HOLY DAY",  "A Religious Holiday For Jews ",
"HOLY DAY OF OBLIGATION",   "A Day When Catholics Must Attend Mass And Refrain From Servile Work, And Episcopalians Must Take Communion ",
"MOVABLE FEAST",    "A Religious Holiday That Falls On Different Dates In Different Years ",
"YOM KIPPUR",   "Judaism A Solemn And Major Fast Day On The Jewish Calendar",
"SAINT AGNES'S EVE",    "A Christian Holy Day ",
"MARTINMAS",    "The Feast Of Saint Martin",
"INDIAN SUMMER",    "A Period Of Unusually Warm Weather In The Autumn ",
"ANNUNCIATION", "A Festival Commemorating The Announcement Of The Incarnation By The Angel Gabriel To The Virgin Mary",
"MICHAELMAS",   "Honoring The Archangel Michael",
"MICHAELMASTIDE",   "The Season Of Michaelmas ",
"CANDLEMAS",    "Feast Day Commemorating The Presentation Of Christ In The Temple",
"GROUNDHOG DAY",    "If The Ground Hog Emerges And Sees His Shadow On This Day, There Will Be 6 More Weeks Of Winter ",
"LINCOLN'S BIRTHDAY",   "The Day On Which President Abraham Lincoln Is Remembered ",
"VALENTINE DAY",    "A Day For The Exchange Of Tokens Of Affection ",
"WASHINGTON'S BIRTHDAY",    "The Day On Which George Washington Is Remembered ",
"PRESIDENTS' DAY",  "The Third Monday In February",
"TEXAS INDEPENDENCE DAY",   "Texans Celebrate The Anniversary Of Texas' Declaration Of Independence From Mexico In 1836 ",
"ST PATRICK'S DAY", "A Day Observed By The Irish To Commemorate The Patron Saint Of Ireland ",
"EASTER",   "A Christian Celebration Of The Resurrection Of Christ",
"EASTER SUNDAY",    "The Day In March Or April On Which The Festival Of Easter Is Celebrated ",
"APRIL FOOLS'", "The First Day Of April Which Is Celebrated By Playing Practical Jokes ",
"PAN AMERICAN DAY", "A Day Celebrating Political And Economic Unity Among American Countries ",
"PATRIOT'S DAY",    "The 3Rd Monday In April",
"MAY DAY",  "Observed In Many Countries To Celebrate The Coming Of Spring",
"MOTHER'S DAY", "Second Sunday In May ",
"ARMED FORCES DAY", "The 3Rd Saturday In May ",
"MEMORIAL DAY", "Legal Holiday In The United States, Last Monday In May",
"JEFFERSON DAVIS' BIRTHDAY",    "Celebrated In Southern United States ",
"FLAG DAY", "Commemorating The Adoption Of The United States Flag In 1777 ",
"FATHER'S DAY", "Us: Third Sunday In June ",
"INDEPENDENCE DAY", "A Legal Holiday In The United States ",
"LAMMAS",   "Commemorates Saint Peter'S Miraculous Deliverance From Prison",
"LAMMASTIDE",   "The Season Of Lammas ",
"LABOR DAY",    "First Monday In September In The United States And Canada ",
"CITIZENSHIP DAY",  "Celebrated In The United States ",
"AMERICAN INDIAN DAY",  "Us: The 4Th Friday In September ",
"COLUMBUS DAY", "A Legal Holiday Commemorating The Discovery Of America By Christopher Columbus ",
"UNITED NATIONS DAY",   "A Day For Celebrating The Founding Of The United Nations ",
"HALLOWEEN",    "The Evening Before All Saints' Day",
"PASCH",    "The Christian Festival Of Easter ",
"EASTERTIDE",   "The Easter Season ",
"PALM SUNDAY",  "Sunday Before Easter ",
"PASSION SUNDAY",   "Second Sunday Before Easter ",
"GOOD FRIDAY",  "Friday Before Easter ",
"LOW SUNDAY",   "The Sunday Following Easter ",
"HOLY SATURDAY",    "The Saturday Before Easter",
"HOLY INNOCENTS' DAY",  "December 28, Commemorating Herod'S Slaughter Of The Children Of Bethlehem ",
"SEPTUAGESIMA", "The 3Rd Sunday Before Lent Or The 9Th Before Easter ",
"QUINQUAGESIMA",    "The Sunday Before Ash Wednesday The Beginning Of Lent ",
"QUADRAGESIMA", "The First Sunday In Lent ",
"TRINITY SUNDAY",   "Eighth Sunday After Easter ",
"ROGATION DAY", "One Of The Three Days Before Ascension Day",
"SOLEMNITY OF MARY",    "Roman Catholic Church A Holy Day Of Obligation ",
"ASCENSION",    "Christianity Celebration Of The Ascension Of Christ Into Heaven",
"CIRCUMCISION", "Roman Catholic Church And Anglican Church Feast Day Celebrating The Circumcision Of Jesus",
"MAUNDY THURSDAY",  "The Thursday Before Easter",
"CORPUS CHRISTI",   "Thursday After Trinity Sunday",
"SAINTS PETER AND PAUL",    "First Celebrated In The 3Rd Century ",
"ASSUMPTION",   "Celebration In The Roman Catholic Church Of The Virgin Mary'S Being Taken Up Into Heaven When Her Earthly Life Ended",
"DORMITION",    "Celebration In The Eastern Orthodox Church Of The Virgin Mary'S Being Taken Up Into Heaven When Her Earthly Life Ended",
"EPIPHANY", "Twelve Days After Christmas",
"SAINT JOSEPH", "A Christian Holy Day ",
"TWELFTHTIDE",  "The Season Of Epiphany ",
"TWELFTH NIGHT",    "Eve Of Twelfth Day",
"ALL SAINTS' DAY",  "A Christian Feast Day Honoring All The Saints",
"IMMACULATE CONCEPTION",    "Roman Catholic Holy Day First Celebrated In 1854 ",
"ALLHALLOWTIDE",    "The Season Of All Saints' Day ",
"ALL SOULS' DAY",   "A Day Of Supplication For All The Souls In Purgatory ",
"ASH WEDNESDAY",    "The 7Th Wednesday Before Easter",
"EMBER DAY",    "A Day Set Aside For Fasting And Prayer ",
"PASSOVER", "Judaism A Jewish Festival Traditionally 8 Days From Nissan 15 Celebrating The Exodus Of The Israelites From Egypt ",
"CHRISTMAS",    "A Christian Holiday Celebrating The Birth Of Christ",
"CHRISTMAS EVE",    "The Day Before Christmas ",
"BOXING DAY",   "First Weekday After Christmas ",
"PURIM",    "Judaism A Jewish Holy Day Commemorating Their Deliverance From Massacre By Haman ",
"SHAVOUS",  "Judaism Jewish Holy Day Celebrated On The Sixth Of Sivan To Celebrate Moses Receiving The Ten Commandments ",
"SHIMCHATH TORAH",  "Judaism A Jewish Holy Day Celebrated On The 22Nd Or 23Rd Of Tishri To Celebrate The Completion Of The Annual Cycle Of Readings Of The Torah ",
"TISHAH B'AV",  "Judaism A Major Fast Day On The Jewish Calendar Commemorating The Destruction Of The Temples In Jerusalem ",
"FAST OF GEDALIAH", "Judaism A Minor Fast Day On Tishri 3 That Commemorates The Killing Of The Jewish Governor Of Judah ",
"FAST OF TEVET",    "Judaism A Minor Fast Day On Tevet 10 Commemorates The Beginning Of The Siege Of Jerusalem And Has Also Been Proclaimed A Memorial Day For The Six Million Jews Who Died In The Holocaust ",
"FAST OF ESTHER",   "Judaism A Minor Fast Day On Adar 13 Commemorates Three Days That Esther Fasted Before Approaching The Persian King On Behalf Of The Jewish People",
"FAST OF THE FIRSTBORN",    "Judaism A Minor Fast Day On Nissan 14 That Is Observed Only By Firstborn Males",
"FAST OF TAMMUZ",   "Judaism A Minor Fast Day On Tammuz 17 When The Walls Of Jerusalem Were Breached ",
"HANUKKAH", "Judaism An Eight-Day Jewish Holiday Commemorating The Rededication Of The Temple Of Jerusalem In 165 Bc ",
"LAG B'OMER",   "Judaism Jewish Holy Day",
"LEGAL HOLIDAY",    "Authorized By Law And Limiting Work Or Official Business ",
"BANK HOLIDAY", "Any Of Several Weekdays When Banks Are Closed",
"COMMONWEALTH DAY", "British, Anniversary Of Queen Victoria'S Birth ",
"DOMINION DAY", "A Legal Holiday In Canada Commemorating Receiving Dominion Status In 1867 ",
"BASTILLE DAY", "A Legal Holiday In France Celebrating The Storming Of The Paris Bastille In 1789 ",
"REMEMBRANCE DAY",  "The Sunday Nearest To November 11 When Those Who Died In World War I And World War Ii Are Commemorated ",
"VETERANS DAY", "A Legal Holiday In The United States",
"THANKSGIVING", "Fourth Thursday In November In The United States",
"VICTORIA DAY", "A Public Holiday In Canada On The Monday On Or Before May 24Th ",
"YEAR", "The Period Of Time That It Takes For A Planet As, E.G., Earth Or Mars To Make A Complete Revolution Around The Sun",
"ANOMALISTIC YEAR", "Time Of The Earth'S Revolution From Perihelion To Perihelion Again",
"YEAR-END", "The End Of A Calendar Year",
"COMMON YEAR",  "A Year That Is Not A Leap Year ",
"LEAP YEAR",    "A Calendar Year With An Extra Day Added In February",
"OFF YEAR", "A Year In Which No Major Political Elections Are Held ",
"CALENDAR YEAR",    "The Year Reckoned From January 1 To December 31 According To Gregorian Calendar ",
"SOLAR YEAR",   "The Time For The Earth To Make One Revolution Around The Sun, Measured Between Two Vernal Equinoxes ",
"LUNAR YEAR",   "A Period Of 12 Lunar Months ",
"FISCAL YEAR",  "Any Accounting Period Of 12 Months ",
"SCHOOL",   "The Period Of Instruction In A School",
"SCHOOL YEAR",  "The Period Of Time Each Year When The School Is Open And People Are Studying ",
"YEAR", "A Period Of Time Containing 365 Or 366 Days",
"ANNUM",    "Latin Year",
"SEMESTER", "Half A Year",
"BIMESTER", "A Period Of 2 Months ",
"OLYMPIAD", "One Of The Four-Year Intervals Between Olympic Games",
"LUSTRUM",  "A Period Of Five Years ",
"DECADE",   "A Period Of 10 Years ",
"CENTURY",  "A Period Of 100 Years ",
"QUADRENNIUM",  "A Period Of Four Years ",
"QUINQUENNIUM", "A Period Of Five Years ",
"QUATTROCENTO", "The 15Th Century In Italian Art And Literature ",
"TWENTIETH CENTURY",    "The Century From 1901 To 2000 ",
"HALF-CENTURY", "A Period Of 50 Years ",
"QUARTER-CENTURY",  "A Period Of 25 Years ",
"MONTH",    "A Time Unit Of Approximately 30 Days",
"QUARTER",  "A Fourth Part Of A Year",
"PHASE OF THE MOON",    "A Time When The Moon Presents A Particular Recurring Appearance ",
"NEW MOON", "The Time At Which The Moon Appears As A Narrow Waxing Crescent ",
"HALF-MOON",    "The Time At Which The Moon Is At First Or Last Quarter When Half Its Face Is Illuminated ",
"FIRST QUARTER",    "The First Fourth Of The Moon'S Period Of Revolution Around The Earth ",
"LAST QUARTER", "The Last Fourth Of The Moon'S Period Of Revolution Around The Earth ",
"FULL MOON",    "The Time When The Moon Is Fully Illuminated",
"HARVEST MOON", "The Full Moon Nearest The September Equinox ",
"LUNAR MONTH",  "The Period Between Successive New Moons 29.531 Days ",
"ANOMALISTIC MONTH",    "Period Between Successive Perigees",
"SIDEREAL TIME",    "Measured By The Diurnal Motion Of Stars ",
"SIDEREAL DAY", "The Time For One Complete Rotation Of The Earth Relative To A Particular Star, About 4 Minutes Shorter Than A Mean Solar Day ",
"LUNAR DAY",    "The Period Of Time Taken For The Moon To Make One Full Rotation On Its Axis About 27.3 Sidereal Days ",
"SIDEREAL YEAR",    "The Time For The Earth To Make One Complete Revolution Around The Sun, Relative To The Fixed Stars ",
"SIDEREAL HOUR",    "1/24 Of A Sidereal Day ",
"SIDEREAL MONTH",   "Period Between Successive Conjunctions With A Star, 27.322 Days ",
"SOLAR MONTH",  "One-Twelfth Of A Solar Or Tropical Year ",
"CALENDAR MONTH",   "One Of The Twelve Divisions Of The Calendar Year",
"GREGORIAN CALENDAR MONTH", "A Month In The Gregorian Calendar ",
"JANUARY",  "The First Month Of The Year",
"MID-JANUARY",  "The Middle Part Of January ",
"FEBRUARY", "The Month Following January And Preceding March ",
"MID-FEBRUARY", "The Middle Part Of February ",
"MARCH",    "The Month Following February And Preceding April ",
"MID-MARCH",    "The Middle Part Of March ",
"APRIL",    "The Month Following March And Preceding May ",
"MID-APRIL",    "The Middle Part Of April ",
"MAY",  "The Month Following April And Preceding June ",
"MID-MAY",  "The Middle Part Of May ",
"JUNE", "The Month Following May And Preceding July ",
"MID-JUNE", "The Middle Part Of June ",
"JULY", "The Month Following June And Preceding August ",
"MID-JULY", "The Middle Part Of July ",
"AUGUST",   "The Month Following July And Preceding September ",
"MID-AUGUST",   "The Middle Part Of August ",
"SEPTEMBER",    "The Month Following August And Preceding October ",
"MID-SEPTEMBER",    "The Middle Part Of September ",
"OCTOBER",  "The Month Following September And Preceding November ",
"MID-OCTOBER",  "The Middle Part Of October ",
"NOVEMBER", "The Month Following October And Preceding December ",
"MID-NOVEMBER", "The Middle Part Of November ",
"DECEMBER", "The Last 12Th Month Of The Year ",
"MID-DECEMBER", "The Middle Part Of December ",
"JEWISH CALENDAR MONTH",    "A Month In The Jewish Calendar ",
"TISHRI",   "The First Month Of The Civil Year",
"HESHVAN",  "The Second Month Of The Civil Year",
"KISLEV",   "The Third Month Of The Civil Year",
"TEBET",    "The Fourth Month Of The Civil Year",
"SHEBAT",   "The Fifth Month Of The Civil Year: The Eleventh Month Of The Ecclesiastical Year In The Jewish Calendar In January And February ",
"ADAR", "The Sixth Month Of The Civil Year",
"VEADAR",   "Included Seven Times In Every 19 Years ",
"NISAN",    "The Seventh Month Of The Civil Year",
"IYAR", "The Eighth Month Of The Civil Year",
"SIVAN",    "The Ninth Month Of The Civil Year",
"TAMMUZ",   "The Tenth Month Of The Civil Year",
"AB",   "The Eleventh Month Of The Civil Year",
"ELUL", "The Twelfth Month Of The Civil Year",
"ISLAMIC CALENDAR MONTH",   "Any Lunar Month In The Muslim Calendar ",
"MUHARRAM", "The First Month Of The Islamic Calendar ",
"SAFAR",    "The Second Month Of The Islamic Calendar ",
"RABI I",   "The Third Month Of The Islamic Calendar ",
"RABI II",  "The Fourth Month Of The Islamic Calendar ",
"JUMADA I", "The Fifth Month Of The Islamic Calendar ",
"JUMADA II",    "The Sixth Month Of The Islamic Calendar ",
"RAJAB",    "The Seventh Month Of The Islamic Calendar ",
"SHA'BAN",  "The Eighth Month Of The Islamic Calendar ",
"RAMADAN",  "The Ninth Month Of The Islamic Calendar",
"ID AL-FITR",   "A Muslim Day Of Feasting At The End Of Ramadan ",
"SHAWWAL",  "The Tenth Month Of The Islamic Calendar ",
"DHU'L-QA'DAH", "The Eleventh Month Of The Islamic Calendar ",
"DHU'L-HIJJA",  "The Twelfth Month Of The Islamic Calendar And The Season Of The Hajj",
"ID AL-ADHA",   "The 10Th Day Of Dhu'L-Hijja",
"HINDU CALENDAR MONTH", "Any Lunisolar Month In The Hindu Calendar ",
"CHAIT",    "The First Hindu Calendar Month Corresponding To March In The Gregorian Calendar ",
"RAMANAVAMI",   "Hindu Lunar Holiday On The 9Th Day Of Caitra To Celebrate The Birth Of Rama ",
"BAISAKH",  "The Second Month Of The Hindu Calendar ",
"JETH", "The Third Month Of The Hindu Calendar ",
"ASARH",    "The Fourth Month Of The Hindu Calendar ",
"SAWAN",    "The Fifth Month Of The Hindu Calendar ",
"BHADON",   "The Sixth Month Of The Hindu Calendar ",
"ASIN", "The Seventh Month Of The Hindu Calendar ",
"KARTIK",   "The Eighth Month Of The Hindu Calendar ",
"AGHAN",    "The Ninth Month Of The Hindu Calendar ",
"PUS",  "The Tenth Month Of The Hindu Calendar ",
"MAGH", "The Eleventh Month Of The Hindu Calendar",
"MESASAMKRANTI",    "Hindu Solar Holiday At The Beginning Of The New Astrological Year When The Sun Enters The Constellation Aries ",
"PHAGUN",   "The Twelfth Month Of The Hindu Calendar ",
"SAINT'S DAY",  "A Day Commemorating A Saint ",
"NAME DAY", "The Feast Day Of A Saint Whose Name One Bears ",
"SOLSTICE", "Either Of The Two Times Of The Year When The Sun Is At Its Greatest Distance From The Celestial Equator ",
"SUMMER SOLSTICE",  "June 21, When The Sun Is At Its Northernmost Point ",
"MIDSUMMER DAY",    "A Quarter Day In England, Wales, And Ireland ",
"MIDSUMMER EVE",    "The Night Before Midsummer Day ",
"SCHOOL DAY",   "Any Day On Which School Is In Session",
"SPEECH DAY",   "An Annual Day In The Schools When Speeches Are Made And Prizes Are Distributed ",
"WASHDAY",  "A Day Set Aside For Doing Household Laundry ",
"WEDDING DAY",  "The Day Of A Wedding ",
"WEDDING NIGHT",    "The Night After The Wedding When Bride And Groom Sleep Together ",
"WINTER SOLSTICE",  "December 22, When The Sun Is At Its Southernmost Point ",
"EQUINOX",  "Either Of Two Times Of The Year When The Sun Crosses The Plane Of The Earth'S Equator And Day And Night Are Of Equal Length ",
"VERNAL EQUINOX",   "March 21 ",
"AUTUMNAL EQUINOX", "September 22 ",
"NORUZ",    "Persian The New Year Holiday In Iran And Azerbaijan And Afghanistan And Pakistan And Parts Of India And Among The Kurds",
"TIME LIMIT",   "A Time Period Within Which Something Must Be Done Or Completed ",
"LIMITATION",   "Law A Time Period After Which Suits Cannot Be Brought",
"TERM", "A Limited Period Of Time",
"PRISON TERM",  "The Period Of Time A Prisoner Is Imprisoned",
"HARD TIME",    "A Term Served In A Maximum Security Prison ",
"LIFE SENTENCE",    "A Prison Term Lasting As Long As The Prisoner Lives",
"SCHOOL TERM",  "The Time During Which A School Holds Classes",
"SUMMER SCHOOL",    "An Academic Session During The Summer",
"MIDTERM",  "Middle Of An Academic Term Or A Political Term In Office ",
"TRIMESTER",    "One Of Three Divisions Of An Academic Year ",
"QUARTER",  "One Of Four Periods Into Which The School Year Is Divided",
"GESTATION",    "The Period During Which An Embryo Develops About 266 Days In Humans ",
"FIRST TRIMESTER",  "Time Period Extending From The First Day Of The Last Menstrual Period Through 12 Weeks Of Gestation ",
"SECOND TRIMESTER", "Time Period Extending From The 13Th To The 27Th Week Of Gestation ",
"THIRD TRIMESTER",  "Time Period Extending From The 28Th Week Of Gestation Until Delivery ",
"REFRACTORY PERIOD",    "Neurology The Time After A Neuron Fires Or A Muscle Fiber Contracts During Which A Stimulus Will Not Evoke A Response ",
"BELL", "Nautical Each Of The Eight Half-Hour Units Of Nautical Time Signaled By Strokes Of A Ship'S Bell",
"HOUR", "A Period Of Time Equal To 1/24Th Of A Day",
"HALF-HOUR",    "A Half Of An Hour ",
"QUARTER-HOUR", "A Quarter Of An Hour ",
"NONE", "A Canonical Hour That Is The Ninth Hour Of The Day Counting From Sunrise ",
"HOUR", "A Special And Memorable Period",
"HAPPY HOUR",   "The Time Of Day When A Bar Sells Alcoholic Drinks At A Reduced Price ",
"RUSH HOUR",    "The Times At The Beginning And End Of The Working Day When Many People Are Traveling To Or From Work ",
"ZERO HOUR",    "The Time Set For The Start Of An Action Or Operation ",
"CANONICAL HOUR",   "Roman Catholic Church One Of Seven Specified Times For Prayer ",
"MATINS",   "The First Canonical Hour",
"TERCE",    "The Third Canonical Hour",
"SEXT", "The Fourth Of The Seven Canonical Hours",
"NONES",    "The Fifth Of The Seven Canonical Hours",
"VESPERS",  "The Sixth Of The Seven Canonical Hours Of The Divine Office",
"COMPLINE", "Last Of The Seven Canonical Hours Just Before Retiring ",
"MAN HOUR", "A Time Unit Used In Industry For Measuring Work ",
"SILLY SEASON", "A Time Usually Late Summer Characterized By Exaggerated News Stories About Frivolous Matters For Want Of Real News ",
"GOLDEN AGE",   "Classical Mythology The First And Best Age Of The World, A Time Of Ideal Happiness, Prosperity, And Innocence",
"SILVER AGE",   "Classical Mythology The Second Age Of The World, Characterized By Opulence And Irreligion",
"BRONZE AGE",   "Classical Mythology The Third Age Of The World, Marked By War And Violence ",
"IRON AGE", "Classical Mythology The Last And Worst Age Of The World ",
"STONE AGE",    "Archeology The Earliest Known Period Of Human Culture, Characterized By The Use Of Stone Implements ",
"EOLITHIC AGE", "The Earliest Part Of The Stone Age Marked By The Earliest Signs Of Human Culture ",
"PALEOLITHIC AGE",  "Second Part Of The Stone Age Beginning About 750,000 To 500,000 Years Bc And Lasting Until The End Of The Last Ice Age About 8,500 Years Bc ",
"LOWER PALEOLITHIC",    "The Oldest Part Of The Paleolithic Age With The Emergence Of The Hand Ax",
"MIDDLE PALEOLITHIC",   "The Time Period Of Neanderthal Man",
"UPPER PALEOLITHIC",    "The Time Period During Which Only Modern Homo Sapiens Was Known To Have Existed",
"MESOLITHIC AGE",   "Middle Part Of The Stone Age Beginning About 15,000 Years Ago ",
"NEOLITHIC AGE",    "Latest Part Of The Stone Age Beginning About 10,000 Bc In The Middle East But Later Elsewhere ",
"GREAT YEAR",   "Time Required For One Complete Cycle Of The Precession Of The Equinoxes, About 25,800 Years ",
"REGULATION TIME",  "Sports The Normal Prescribed Duration Of A Game",
"OVERTIME", "Playing Time Beyond Regulation, To Break A Tie ",
"EXTRA INNINGS",    "Overtime Play Until One Team Is Ahead At The End Of An Inning",
"OVERTIME PERIOD",  "A Period Of Overtime Play To Resolve A Tie",
"TIEBREAKER",   "Overtime Play In Order To Break A Tie",
"SUDDEN DEATH", "Sports Overtime In Which Play Is Stopped As Soon As One Contestant Scores",
"MINUTE",   "A Unit Of Time Equal To 60 Seconds Or 1/60Th Of An Hour",
"SECOND",   "1/60 Of A Minute",
"LEAP SECOND",  "A Second As Measured By An Atomic Clock Added To Or Subtracted From Greenwich Mean Time In Order To Compensate For Slowing In The Earth'S Rotation ",
"ATTOSECOND",   "One Quintillionth 10^-18 Of A Second",
"FEMTOSECOND",  "One Quadrillionth 10^-15 Of A Second",
"PICOSECOND",   "One Trillionth 10^-12 Of A Second",
"NANOSECOND",   "One Billionth 10^-9 Of A Second",
"MICROSECOND",  "One Millionth 10^-6 Of A Second",
"MILLISECOND",  "One Thousandth 10^-3 Of A Second ",
"SEASON",   "One Of The Natural Periods Into Which The Year Is Divided By The Equinoxes And Solstices Or Atmospheric Conditions",
"FALL", "The Season When The Leaves Fall From The Trees",
"SPRING",   "The Season Of Growth",
"SUMMER",   "The Warmest Season Of The Year",
"DOG DAYS", "The Hot Period Between Early July And Early September",
"WINTER",   "The Coldest Season Of The Year",
"MIDWINTER",    "The Middle Of Winter ",
"GROWING SEASON",   "The Season During Which A Crop Grows Best ",
"SEEDTIME", "The Time During Which Seeds Should Be Planted ",
"SHEEPSHEARING",    "The Time Or Season When Sheep Are Sheared ",
"HOLIDAY SEASON",   "A Time When Many People Take Holidays ",
"HIGH SEASON",  "The Season When Travel Is Most Active And Rates Are Highest",
"OFF-SEASON",   "The Season When Travel Is Least Active And Rates Are Lowest ",
"RAINY SEASON", "One Of The Two Seasons In Tropical Climates ",
"MONSOON",  "Rainy Season In Southern Asia When The Southwestern Monsoon Blows, Bringing Heavy Rains ",
"DRY SEASON",   "One Of The Two Seasons In Tropical Climates ",
"PRESEASON",    "A Period Prior To The Beginning Of The Regular Season Which Is Devoted To Training And Preparation ",
"SPRING TRAINING",  "Preseason Training During The Spring ",
"BASEBALL SEASON",  "The Season When Baseball Is Played ",
"TRIPLE-CROWN SEASON",  "A Season Of Baseball During Which A Player Wins The Triple Crown ",
"BASKETBALL SEASON",    "The Season When Basketball Is Played ",
"EXHIBITION SEASON",    "The Time Before The Regular Games Begin When Football Or Baseball Teams Play Practice Games ",
"FISHING SEASON",   "The Season During Which It Is Legal To Catch Fish ",
"FOOTBALL SEASON",  "The Season When Football Is Played ",
"HOCKEY SEASON",    "The Season When Hockey Is Played ",
"HUNTING SEASON",   "The Season During Which It Is Legal To Kill A Particular Species ",
"SOCIAL SEASON",    "The Season For Major Social Events ",
"THEATRICAL SEASON",    "The Season When New Plays Are Produced ",
"ADVENT",   "The Season Including The Four Sundays Preceding Christmas ",
"ADVENT SUNDAY",    "The First Of The Four Sundays During Advent ",
"SHROVETIDE",   "Immediately Preceding Lent ",
"MARDI GRAS",   "The Last Day Before Lent ",
"LENT", "A Period Of 40 Weekdays From Ash Wednesday To Holy Saturday ",
"PENTECOST",    "Seventh Sunday After Easter",
"WHITMONDAY",   "The Day After Whitsunday",
"WHIT-TUESDAY", "The Day After Whitmonday ",
"WHITSUN",  "Christian Holiday",
"LONG TIME",    "A Prolonged Period Of Time",
"MONTH OF SUNDAYS", "A Time Perceived As Long",
"LONG RUN", "A Period Of Time Sufficient For Factors To Work Themselves Out",
"EON",  "An Immeasurably Long Period Of Time",
"ETERNITY", "Time Without End ",
"ALPHA AND OMEGA",  "The First And Last",
"BLUE MOON",    "A Long Time",
"YEAR DOT", "As Long Ago As Anyone Can Remember",
"DROUGHT",  "A Prolonged Shortage",
"MOMENT",   "A Particular Point In Time",
"ELEVENTH HOUR",    "The Latest Possible Moment",
"MOMENT OF TRUTH",  "A Crucial Moment On Which Much Depends ",
"PINPOINT", "A Very Brief Moment",
"HIGH TIME",    "The Latest Possible Moment",
"OCCASION", "The Time Of A Particular Event",
"MEAL", "Any Of The Occasions For Eating Food That Occur By Custom Or Habit At More Or Less Fixed Times ",
"PSYCHOLOGICAL MOMENT", "The Most Appropriate Time For Achieving A Desired Effect ",
"WEE",  "A Short Time",
"WHILE",    "A Period Of Indeterminate Length Usually Short Marked By Some Action Or Condition",
"COLD SPELL",   "A Spell Of Cold Weather ",
"HOT SPELL",    "A Spell Of Hot Weather ",
"MOMENT",   "An Indefinitely Short Time",
"BLINK OF AN EYE",  "A Very Short Time As The Time It Takes The Eye To Blink Or The Heart To Beat",
"EPHEMERA", "Something Transitory",
"ERA",  "A Major Division Of Geological Time",
"EPOCH",    "A Unit Of Geological Time That Is A Subdivision Of A Period And Is Itself Divided Into Ages ",
"CALIPHATE",    "The Era Of Islam'S Ascendancy From The Death Of Mohammed Until The 13Th Century",
"CHRISTIAN ERA",    "The Time Period Beginning With The Supposed Year Of Christ'S Birth ",
"YEAR OF GRACE",    "Any Year Of The Christian Era ",
"GENERATION",   "The Normal Time Between Successive Generations",
"ANNIVERSARY",  "The Date On Which An Event Occurred In Some Previous Year Or The Celebration Of It ",
"BIRTHDAY", "An Anniversary Of The Day On Which A Person Was Born Or The Celebration Of It ",
"JUBILEE",  "A Special Anniversary Or The Celebration Of It ",
"DIAMOND JUBILEE",  "An Anniversary Celebrating The Passage Of 60 Years ",
"SILVER JUBILEE",   "An Anniversary Celebrating The Passage Of 25 Years ",
"WEDDING ANNIVERSARY",  "The Anniversary Of The Day On Which You Were Married Or The Celebration Of It ",
"SILVER WEDDING ANNIVERSARY",   "The 25Th Wedding Anniversary ",
"GOLDEN WEDDING ANNIVERSARY",   "The 50Th Wedding Anniversary ",
"DIAMOND WEDDING ANNIVERSARY",  "The 60Th Wedding Anniversary ",
"SEMICENTENNIAL",   "The 50Th Anniversary Or The Celebration Of It ",
"CENTENNIAL",   "The 100Th Anniversary Or The Celebration Of It ",
"SESQUICENTENNIAL", "The 150Th Anniversary Or The Celebration Of It ",
"BICENTENNIAL", "The 200Th Anniversary Or The Celebration Of It ",
"TERCENTENNIAL",    "The 300Th Anniversary Or The Celebration Of It ",
"QUATERCENTENNIAL", "The 400Th Anniversary Or The Celebration Of It ",
"QUINCENTENNIAL",   "The 500Th Anniversary Or The Celebration Of It ",
"BIMILLENNIUM", "The 2000Th Anniversary Or The Celebration Of It ",
"TIME IMMEMORIAL",  "The Distant Past Beyond Memory ",
"AULD LANGSYNE",    "Past Times Remembered With Nostalgia ",
"BY-AND-BY",    "An Indefinite Time In The Future",
"CHAPTER",  "Any Distinct Period In History Or In A Person'S Life",
"ANTIQUITY",    "The Historic Period Preceding The Middle Ages In Europe ",
"HISTORIC PERIOD",  "An Era Of History Having Some Distinctive Feature",
"PREHISTORY",   "The Time During The Development Of Human Culture Before The Appearance Of The Written Word ",
"MODERN ERA",   "The Present Or Recent Times ",
"INFORMATION AGE",  "A Period Beginning In The Last Quarter Of The 20Th Century When Information Became Easily Accessible Through Publications And Through The Manipulation Of Information By Computers And Computer Networks ",
"ICE AGE",  "Any Period Of Time During Which Glaciers Covered A Large Part Of The Earth'S Surface",
"JAZZ AGE", "The 1920S In The United States Characterized In The Novels Of F. Scott Fitzgerald As A Period Of Wealth, Youthful Exuberance, And Carefree Hedonism ",
"CHUKKER",  "Polo One Of Six Divisions Into Which A Polo Match Is Divided ",
"INNING",   "Baseball One Of Nine Divisions Of Play During Which Each Team Has A Turn At Bat ",
"TOP",  "The First Half Of An Inning",
"BOTTOM",   "The Second Half Of An Inning",
"SET",  "A Unit Of Play In Tennis Or Squash",
"GAME", "Tennis A Division Of Play During Which One Player Serves ",
"TURN", "Sports A Division During Which One Team Is On The Offensive ",
"PLAYING PERIOD",   "In Games Or Plays Or Other Performances The Time During Which Play Proceeds",
"FIRST PERIOD", "The First Division Into Which The Play Of A Game Is Divided ",
"SECOND PERIOD",    "The Second Division Into Which The Play Of A Game Is Divided ",
"FINAL PERIOD", "The Final Division Into Which The Play Of A Game Is Divided ",
"HALF", "One Of Two Divisions Into Which Some Games Or Performances Are Divided: The Two Divisions Are Separated By An Interval ",
"FIRST HALF",   "The First Of Two Halves Of Play ",
"SECOND HALF",  "The Second Of Two Halves Of Play ",
"OVER", "Cricket The Division Of Play During Which Six Balls Are Bowled At The Batsman By One Player From The Other Team From The Same End Of The Pitch ",
"MAIDEN OVER",  "Cricket An Over In Which No Runs Are Scored ",
"BAROQUE",  "The Historic Period From About 1600 Until 1750 When The Baroque Style Of Art, Architecture, And Music Flourished In Europe ",
"MIDDLE AGES",  "The Period Of History Between Classical Antiquity And The Italian Renaissance ",
"RENAISSANCE",  "The Period Of European History At The Close Of The Middle Ages And The Rise Of The Modern World",
"ITALIAN RENAISSANCE",  "The Early Period When Italy Was The Center Of The Renaissance ",
"INDUSTRIAL REVOLUTION",    "The Transformation From An Agricultural To An Industrial Nation ",
"REIGN OF TERROR",  "The Historic Period 1793-94 During The French Revolution When Thousands Were Executed",
"REIGN",    "The Period During Which A Monarch Is Sovereign",
"TURN OF THE CENTURY",  "The Period From About Ten Years Before To Ten Years After A New Century ",
"HARLEM RENAISSANCE",   "A Period In The 1920S When African-American Achievements In Art And Music And Literature Flourished ",
"NEW DEAL", "The Historic Period 1933-1940 In The United States During Which President Franklin Roosevelt'S Economic Policies Were Implemented ",
"RECONSTRUCTION",   "The Period After The American Civil War When The Southern States Were Reorganized And Reintegrated Into The Union",
"RESTORATION",  "The Reign Of Charles Ii In England",
"PRINT RUN",    "The Period That Presses Run To Produce An Issue Of A Newspaper ",
"RUN",  "The Continuous Period Of Time During Which Something A Machine Or A Factory Operates Or Continues In Operation",
"RUN-TIME", "Computer Science The Length Of Time It Takes To Execute A Software Program ",
"SPLIT RUN",    "A Print Run Of A Newspaper During Which Some Articles Or Advertisements Are Changed To Produce A Different Edition ",
"SPACE AGE",    "The Age Beginning With The First Space Travel",
"TONIGHT",  "The Present Or Immediately Coming Night ",
"OFFING",   "The Near Or Foreseeable Future",
"MANANA",   "An Indefinite Time In The Future ",
"COMMON TIME",  "A Time Signature Indicating Four Beats To The Bar ",
"DUPLE TIME",   "Musical Time With Two Beats In Each Bar ",
"TRIPLE TIME",  "Musical Time With Three Beats In Each Bar ",
"TEMPO",    "Music The Speed At Which A Composition Is To Be Played ",
"IN TIME",  "In The Correct Rhythm",
"ACCELERANDO",  "A Gradually Increasing Tempo Of Music",
"ALLEGRETTO",   "A Quicker Tempo Than Andante But Not As Fast As Allegro ",
"ALLEGRO",  "A Brisk And Lively Tempo ",
"ALLEGRO CON SPIRITO",  "Lively With Spirit ",
"ANDANTE",  "A Moderately Slow Tempo A Walking Pace ",
"MENO MOSSO",   "Played At Reduced Speed",
"RUBATO",   "A Flexible Tempo",
"BEGINNING",    "The Time At Which Something Is Supposed To Begin",
"TERMINUS A QUO",   "Earliest Limiting Point ",
"PRESIDENCY",   "The Tenure Of A President",
"VICE-PRESIDENCY",  "The Tenure Of A Vice President ",
"MIDDLE",   "Time Between The Beginning And The End Of A Temporal Period",
"END",  "The Point In Time At Which Something Ends",
"DEEP", "The Central And Most Intense Or Profound Part",
"STOPPING POINT",   "The Temporal End",
"CEASE",    "`Cease' Is A Noun Only In The Phrase `Without Cease' End ",
"FAG END",  "The Time Of The Last Part Of Something",
"FIN DE SIECLE",    "The End Of A Century, Especially The 19Th Century ",
"LAST GASP",    "The Point Of Death Or Exhaustion Or Completion",
"TERMINATION",  "A Coming To An End Of A Contract Period",
"TERMINUS AD QUEM", "Final Or Latest Limiting Point ",
"THRESHOLD",    "The Starting Point For A New State Or Experience",
"SEEK TIME",    "Computer Science The Time It Takes For A Read/Write Head To Move To A Specific Data Track ",
"TRACK-TO-TRACK SEEK TIME", "Computer Science The Time It Takes For A Read/Write Head To Move To An Adjacent Data Track ",
"TIME INTERVAL",    "A Definite Length Of Time Marked Off By Two Instants ",
"TIME CONSTANT",    "Electronics The Time Required For The Current Or Voltage In A Circuit To Rise Or Fall Exponentially Through Approximately 63 Per Cent Of Its Amplitude ",
"TIME SLOT",    "A Time Assigned On A Schedule Or Agenda",
"LUNITIDAL INTERVAL",   "Interval Between The Moon'S Transit Of A Particular Meridian And The Next High Tide At That Meridian ",
"ABSENCE",  "The Time Interval During Which Something Or Somebody Is Away",
"PAUSE",    "A Time Interval During Which There Is A Temporary Cessation Of Something ",
"LAPSE",    "A Break Or Intermission In The Occurrence Of Something",
"BLACKOUT", "A Suspension Of Radio Or Tv Broadcasting ",
"CAESURA",  "A Pause Or Interruption As In A Conversation",
"DEAD AIR", "An Inadvertent Interruption In A Broadcast During Which There Is No Sound ",
"DELAY",    "Time During Which Some Action Is Awaited",
"EXTENSION",    "A Mutually Agreed Delay In The Date Set For The Completion Of A Job Or Payment Of A Debt",
"HALFTIME", "An Intermission Between The First And Second Half Of A Game ",
"INTERLUDE",    "An Intervening Period Or Episode ",
"ENTR'ACTE",    "The Interlude Between Two Acts Of A Play ",
"INTERIM",  "The Time Between One Event, Process, Or Period And Another",
"LATENT PERIOD",    "The Time That Elapses Before The Presence Of A Disease Is Manifested By Symptoms ",
"REACTION TIME",    "The Time That Elapses Between A Stimulus And The Response To It ",
"ETERNITY", "A Seemingly Endless Time Interval Waiting ",
"INTERREGNUM",  "The Time Between Two Reigns, Governments, Etc. ",
"SLEEP",    "A Period Of Time Spent Sleeping",
"BEAUTY SLEEP", "Sleep Before Midnight ",
"KIP",  "Sleep",
"RESPITE",  "A Pause For Relaxation",
"TIME-OUT", "A Brief Suspension Of Play",
"LETUP",    "A Pause During Which Things Are Calm Or Activities Are Diminished",
"BREATH",   "A Short Respite ",
"LEASE",    "The Period Of Time During Which A Contract Conveying Property To A Person Is In Effect ",
"HALF LIFE",    "The Time Required For Something To Fall To Half Its Initial Value In Particular, The Time For Half The Atoms In A Radioactive Substance To Disintegrate ",
"RELAXATION TIME",  "The Time Constant Of An Exponential Return Of A System To Equilibrium After A Disturbance ",
"MORATORIUM",   "A Legally Authorized Postponement Before Some Obligation Must Be Discharged ",
"RETARDATION",  "The Extent To Which Something Is Delayed Or Held Back ",
"TIDE", "There Are Usually Two High And Two Low Tides Each Day ",
"ACCELERATION", "Physics A Rate Of Increase Of Velocity ",
"CENTRIPETAL ACCELERATION", "The Acceleration Toward The Center That Holds A Satellite In Elliptical Orbit ",
"DECELERATION", "Physics A Rate Of Decrease In Velocity ",
"ATTRITION RATE",   "The Rate Of Shrinkage In Size Or Number ",
"BIRTHRATE",    "The Ratio Of Live Births In An Area To The Population Of That Area",
"BITS PER SECOND",  "Computer Science The Rate At Which Data Is Transferred As By A Modem ",
"CRIME RATE",   "The Ratio Of Crimes In An Area To The Population Of That Area",
"DATA RATE",    "The Rate At Which Circuits Or Other Devices Operate When Handling Digital Information ",
"DEATHRATE",    "The Ratio Of Deaths In An Area To The Population Of That Area",
"DOSE RATE",    "The Quantity Of Radiation Absorbed Per Unit Time ",
"ERYTHROCYTE SEDIMENTATION RATE",   "The Rate At Which Red Blood Cells Settle Out In A Tube Of Blood Under Standardized Conditions",
"FLOW", "The Amount Of Fluid That Flows In A Given Time ",
"CARDIAC OUTPUT",   "The Amount Of Blood Pumped Out By The Ventricles In A Given Period Of Time",
"FLUX", "The Rate Of Flow Of Energy Or Particles Across A Given Surface ",
"FREQUENCY",    "The Number Of Occurrences Within A Given Time Period",
"GIGAHERTZ",    "1,000,000,000 Periods Per Second ",
"GROWTH RATE",  "The Rate Of Increase In Size Per Unit Time ",
"ISOMETRY", "The Growth Rates In Different Parts Of A Growing Organism Are The Same ",
"HERTZ",    "The Unit Of Frequency",
"INFLATION RATE",   "The Rate Of Change Of Prices As Indicated By A Price Index Calculated On A Monthly Or Annual Basis ",
"JERK", "Mechanics The Rate Of Change Of Acceleration ",
"KNOT", "Of Ships And Wind A Unit Of Speed Equal To One Nautical Mile Per Hour Or About 1.15 Statute Miles Per Hour ",
"KILOHERTZ",    "One Thousand Periods Per Second ",
"KILOMETERS PER HOUR",  "The Ratio Of The Distance Traveled In Kilometers To The Time Spent Traveling In Hours ",
"MEGAHERTZ",    "One Million Periods Per Second ",
"TERAHERTZ",    "One Trillion Periods Per Second ",
"METABOLIC RATE",   "Rate Of Metabolism",
"MILES PER HOUR",   "The Ratio Of The Distance Traveled In Miles To The Time Spent Traveling In Hours ",
"PACE", "The Rate Of Moving Especially Walking Or Running ",
"PULSE",    "The Rate At Which The Heart Beats",
"FEMORAL PULSE",    "Pulse Of The Femoral Artery Felt In The Groin ",
"RADIAL PULSE", "Pulse Of The Radial Artery Felt In The Wrist ",
"RATE OF RETURN",   "The Amount Returned Per Unit Of Time Expressed As A Percentage Of The Cost ",
"RETURN ON INVESTED CAPITAL",   "Corporate Finance The Amount, Expressed As A Percentage, That Is Earned On A Company'S Total Capital Calculated By Dividing The Total Capital Into Earnings Before Interest, Taxes, Or Dividends Are Paid ",
"RESPIRATORY RATE", "The Rate At Which A Person Inhales And Exhales",
"REVOLUTIONS PER MINUTE",   "Rate Of Revolution Of A Motor",
"SAMPLING RATE",    "Telecommunication The Frequency Of Sampling Per Unit Time ",
"NYQUIST RATE", "Telecommunication The Lowest Sampling Rate That Will Permit Accurate Reconstruction Of A Sampled Analog Signal ",
"SOLAR CONSTANT",   "The Rate At Which Radiant Solar Energy Is Received At The Outer Layer Of The Earth'S Atmosphere ",
"SPACING",  "The Time Between Occurrences Of A Repeating Event",
"SPEED",    "Distance Travelled Per Unit Time ",
"QUICK TIME",   "A Normal Marching Pace Of 120 Steps Per Minute ",
"DOUBLE TIME",  "A Fast Marching Pace 180 Steps/Min Or Slow Jog ",
"AIRSPEED", "The Speed Of An Aircraft Relative To The Air In Which It Is Flying ",
"ESCAPE VELOCITY",  "The Minimum Velocity Needed To Escape A Gravitational Field ",
"GROUNDSPEED",  "The Speed Of An Aircraft Relative To The Ground ",
"HYPERVELOCITY",    "Excessive Velocity",
"MUZZLE VELOCITY",  "The Velocity Of A Projectile As It Leaves The Muzzle Of A Gun ",
"PECULIAR VELOCITY",    "Velocity With Respect To The Local Standard Of Rest ",
"RADIAL VELOCITY",  "Velocity Along The Line Of Sight Toward Or Away From The Observer ",
"SPEED OF LIGHT",   "The Speed At Which Light Travels In A Vacuum",
"STEERAGEWAY",  "Nautical The Minimum Rate Of Motion Needed For A Vessel To Be Maneuvered ",
"TERMINAL VELOCITY",    "The Constant Maximum Velocity Reached By A Body Falling Through The Atmosphere Under The Attraction Of Gravity ",
"ATTENDANCE",   "The Frequency With Which A Person Is Present",
"COUNT PER MINUTE", "Frequency Per Minute ",
"SAMPLING FREQUENCY",   "Telecommunication The Frequency Of Sampling A Continuously Varying Signal ",
"NYQUIST FREQUENCY",    "Telecommunication Twice The Maximum Frequency Occurring In The Transmitted Signal ",
"INFANT DEATHRATE", "The Death Rate During The First Year Of Life ",
"NEONATAL MORTALITY",   "The Death Rate During The First 28 Days Of Life ",
"WORDS PER MINUTE", "The Rate At Which Words Are Produced As In Speaking Or Typing ",
"BEATS PER MINUTE", "The Pace Of Music Measured By The Number Of Beats Occurring In 60 Seconds ",
"RATE", "A Magnitude Or Frequency Relative To A Time Unit",
"CHANNEL CAPACITY", "The Maximum Data Rate That Can Be Attained Over A Given Channel ",
"NEUTRON FLUX", "The Rate Of Flow Of Neutrons",
"RADIANT FLUX", "The Rate Of Flow Of Radiant Energy Electromagnetic Waves ",
"LUMINOUS FLUX",    "The Rate Of Flow Of Light Energy ",
"INCUBATION",   "Pathology The Phase In The Development Of An Infection Between The Time A Pathogen Enters The Body And The Time The First Symptoms Appear ",
"CYCLE",    "An Interval During Which A Recurring Sequence Of Events Occurs",
"MENSTRUAL CYCLE",  "A Recurring Cycle Beginning At Menarche And Ending At Menopause In Which The Endometrial Lining Of The Uterus Prepares For Pregnancy",
"FERTILE PERIOD",   "The Time In The Menstrual Cycle When Fertilization Is Most Likely To Be Possible 7 Days Before To 7 Days After Ovulation ",
"MENSTRUAL PHASE",  "The Phase Of The Menstrual Cycle During Which The Lining Of The Uterus Is Shed The First Day Of Menstrual Flow Is Considered Day 1 Of The Menstrual Cycle ",
"MUSTH",    "An Annual Phase Of Heightened Sexual Excitement In The Males Of Certain Large Mammals Especially Elephants",
"SECRETORY PHASE",  "The Second Half Of The Menstrual Cycle After Ovulation",
"LEAD TIME",    "The Time Interval Between The Initiation And The Completion Of A Production Process",
"PERIOD",   "The Interval Taken To Complete One Cycle Of A Regularly Repeating Phenomenon ",
"ORBIT PERIOD", "The Time It Takes To Complete One Full Orbit Around A Celestial Body",
"PHASE",    "A Particular Point In The Time Of A Cycle",
"GENERATION",   "A Stage Of Technological Development Or Innovation",
"MULTISTAGE",   "Occurring In More Than One Stage ",
"APOGEE",   "A Final Climactic Stage",
"TENURE",   "The Term During Which Some Position Is Held ",
"EPISCOPATE",   "The Term Of Office Of A Bishop ",
"SHIFT",    "The Time Period During Which You Are At Work ",
"GO",   "A Time Period For Working After Which You Will Be Relieved By Someone Else",
"TRICK",    "A Period Of Work Or Duty ",
"WATCH",    "A Period Of Time 4 Or 2 Hours During Which Some Of A Ship'S Crew Are On Duty ",
"DOGWATCH", "Either Of Two Short Watches: From 4-6 Pm Or 6-8 Pm ",
"DAY SHIFT",    "The Work Shift During The Day As 8 A.M. To 4 P.M. ",
"EVENING SHIFT",    "The Work Shift During The Evening As 4 P.M. To Midnight ",
"NIGHT SHIFT",  "The Work Shift During The Night As Midnight To 8 A.M. ",
"SPLIT SHIFT",  "A Working Shift Divided Into Two Periods Of Time With Several Hours In Between ",
"PEACETIME",    "A Period Of Time During Which There Is No War ",
"WARTIME",  "A Period Of Time During Which There Is Armed Conflict ",
"GRAVEYARD WATCH",  "A Watch During The Night As From Midnight To 8 A.M. ",
"ENLISTMENT",   "A Period Of Time Spent In Military Service ",
"HONEYMOON",    "The Early Usually Calm And Harmonious Period Of A Relationship",
"INDICTION",    "A 15-Year Cycle Used As A Chronological Unit In Ancient Rome And Adopted In Some Medieval Kingdoms ",
"FLOAT",    "The Time Interval Between The Deposit Of A Check In A Bank And Its Payment ",
"DEPRESSION",   "A Period During The 1930S When There Was A Worldwide Economic Depression And Mass Unemployment ",
"PROHIBITION",  "The Period From 1920 To 1933 When The Sale Of Alcoholic Beverages Was Prohibited In The United States By A Constitutional Amendment ",
"INCUBATION PERIOD",    "The Period Between Infection And The Appearance Of Symptoms Of The Disease ",
"RAINY DAY",    "A Future Time Of Financial Need",
"NOVITIATE",    "The Period During Which You Are A Novice Especially In A Religious Order ",
"FLOWER",   "The Period Of Greatest Prosperity Or Productivity ",
"RULE", "The Duration Of A Monarch'S Or Government'S Power",
"REGENCY",  "The Period From 1811-1820 When The Prince Of Wales Was Regent During George Iii'S Periods Of Insanity ",
"RUNNING TIME", "The Length Of Time That A Movie Or Tv Show Runs ",
"SHOW TIME",    "The Point In Time At Which An Entertainment A Movie Or Television Show Etc. Is Scheduled To Begin ",
"SAFE PERIOD",  "That Time During A Woman'S Menstrual Cycle During Which Conception Is Least Likely To Occur Usually Immediately Before Of After Menstruation ",
"OCTAVE",   "A Feast Day And The Seven Days Following It ",
"THEN", "That Time",
"SHIVA",    "Judaism A Period Of Seven Days Of Mourning After The Death Of Close Relative",
"CLOTTING TIME",    "The Time It Takes For A Sample Of Blood To Clot",
"ROTATIONAL LATENCY",   "Computer Science The Time It Takes For A Specific Block Of Data On A Data Track To Rotate Around To The Read/Write Head ",
"PROBATION",    "A Trial Period During Which An Offender Has Time To Redeem Himself Or Herself ",
"PROCESSING TIME",  "The Time It Takes To Complete A Prescribed Procedure",
"AIR ALERT",    "The Time Period During Which Military And Civilian Agencies Are Prepared For An Enemy Air Attack ",
"COMMAND PROCESSING OVERHEAD TIME", "Computer Science The Processing Time Required By A Device Prior To The Execution Of A Command ",
"GREAT SCHISM", "The Period From 1378 To 1417 During Which There Were Two Papacies In The Roman Catholic Church, One In Rome And One In Avignon ",
"QUESTION TIME",    "A Period During A Parliamentary Session When Members Of British Parliament May Ask Questions Of The Ministers ",
"REAL TIME",    "Computer Science The Time It Takes For A Process Under Computer Control To Occur ",
"SNAP", "A Spell Of Cold Weather",
"STUDY HALL",   "A Period Of Time During The School Day That Is Set Aside For Study ",
"TRANSFIGURATION",  "Christianity A Church Festival Held In Commemoration Of The Transfiguration Of Jesus ",
"USANCE",   "The Period Of Time Permitted By Commercial Usage For The Payment Of A Bill Of Exchange Especially A Foreign Bill Of Exchange ",
"WINDOW",   "The Time Period That Is Considered Best For Starting Or Finishing Something",
"ENTITY",   "That Which Is Perceived Or Known Or Inferred To Have Its Own Distinct Existence Living Or Nonliving ",
"PHYSICAL ENTITY",  "An Entity That Has Physical Existence ",
"ABSTRACTION",  "A General Concept Formed By Extracting Common Features From Specific Examples ",
"THING",    "A Separate And Self-Contained Entity ",
"OBJECT",   "A Tangible And Visible Entity",
"WHOLE",    "An Assemblage Of Parts That Is Regarded As A Single Entity",
"CONGENER", "A Whole A Thing Or Person Of The Same Kind Or Category As Another",
"LIVING THING", "A Living Or Once Living Entity ",
"ORGANISM", "A Living Thing That Has Or Can Develop The Ability To Act Or Function Independently ",
"BENTHOS",  "Organisms Plants And Animals That Live At Or Near The Bottom Of A Sea ",
"DWARF",    "A Plant Or Animal That Is Atypically Small ",
"HETEROTROPH",  "An Organism That Depends On Complex Organic Substances For Nutrition ",
"PARENT",   "An Organism Plant Or Animal From Which Younger Ones Are Obtained ",
"LIFE", "Living Things Collectively",
"BIONT",    "A Discrete Unit Of Living Matter ",
"CELL", "The Basic Structural And Functional Unit Of All Organisms",
"CAUSAL AGENT", "Any Entity That Produces An Effect Or Is Responsible For Events Or Results ",
"PERSON",   "A Human Being",
"ANIMAL",   "A Living Organism Characterized By Voluntary Movement ",
"PLANT",    "A Living Organism Lacking The Power Of Locomotion ",
"NATIVE",   "Indigenous Plants And Animals ",
"NATURAL OBJECT",   "An Object Occurring Naturally",
"SUBSTANCE",    "The Real Physical Matter Of Which A Person Or Thing Consists",
"SUBSTANCE",    "A Particular Kind Or Species Of Matter With Uniform Properties",
"MATTER",   "That Which Has Mass And Occupies Space",
"FOOD", "Any Substance That Can Be Metabolized By An Animal To Give Energy And Build Tissue ",
"NUTRIENT", "Any Substance Such As A Chemical Element Or Inorganic Compound That Can Be Taken In By A Green Plant And Used In Organic Synthesis ",
"ARTIFACT", "A Man-Made Object Taken As A Whole ",
"ARTICLE",  "One Of A Class Of Artifacts",
"PSYCHOLOGICAL FEATURE",    "A Feature Of The Mental Life Of A Living Organism ",
"COGNITION",    "The Psychological Result Of Perception And Learning And Reasoning ",
"MOTIVATION",   "The Psychological Feature That Arouses An Organism To Action Toward A Desired Goal",
"ATTRIBUTE",    "An Abstraction Belonging To Or Characteristic Of An Entity ",
"STATE",    "The Way Something Is With Respect To Its Main Attributes",
"FEELING",  "The Experiencing Of Affective And Emotional States",
"LOCATION", "A Point Or Extent In Space ",
"SHAPE",    "The Spatial Arrangement Of Something As Distinct From Its Substance",
"TIME", "The Continuum Of Experience In Which Events Pass From The Future Through The Present To The Past",
"SPACE",    "The Unlimited Expanse In Which Everything Is Located",
"ABSOLUTE SPACE",   "Physical Space Independent Of What Occupies It ",
"PHASE SPACE",  "An Ideal Space In Which The Coordinate Dimensions Represent The Variables That Are Required To Describe A System Or Substance",
"EVENT",    "Something That Happens At A Given Place And Time ",
"PROCESS",  "A Sustained Phenomenon Or One Marked By Gradual Changes Through A Series Of States",
"ACT",  "Something That People Do Or Cause To Happen ",
"GROUP",    "Any Number Of Entities Members Considered As A Unit ",
"RELATION", "An Abstraction Belonging To Or Characteristic Of Two Entities Or Parts Together ",
"POSSESSION",   "Anything Owned Or Possessed ",
"SOCIAL RELATION",  "A Relation Between Living Organisms Especially Between People ",
"COMMUNICATION",    "Something That Is Communicated By Or To Or Between People Or Groups ",
"MEASURE",  "How Much There Is Or How Many There Are Of Something That You Can Quantify ",
"PHENOMENON",   "Any State Or Process Known Through The Senses Rather Than By Intuition Or Reasoning "
        };


        public bool Contem(string palavraUpper)
        {
            if (ListaSubstantivo12.Contains(palavraUpper))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public string Indice(string palavraUpper)
        {
            var index = ListaSubstantivo12.IndexOf(palavraUpper);
            string next = ListaSubstantivo12[index + 1];
            return next;
        }
        public string Aleatorio()
        {

            var rnd = new Random();
            var valorAleatorio = ListaSubstantivo12[rnd.Next(ListaSubstantivo12.Count)];

            while (ListaSubstantivo12.IndexOf(valorAleatorio) % 2 == 0)
            {
                valorAleatorio = ListaSubstantivo12[rnd.Next(ListaSubstantivo12.Count)];

            }
            return valorAleatorio;
        }
    }
}
